import 'dart:convert';
import '../domain/models/external_biometric_device.dart';

/// Service responsible for synthesizing authentic hardware-level biometric terminal events and raw telemetry.
/// Ensures injected punches are 100% indistinguishable in payload, metadata, and verification structure
/// from punches generated by physical Hikvision MinMoe (DS-K1T343/671) and ZKTeco ADMS devices.
class TerminalEventPayloadSynthesizer {
  /// Synthesizes an authentic [TerminalAttendanceEvent] with complete hardware telemetry.
  static TerminalAttendanceEvent synthesizeHardwareEvent({
    required BiometricTerminalDevice device,
    required String employeeId,
    required String employeeName,
    required String punchType, // 'PUNCH_IN', 'PUNCH_OUT', 'START_BREAK', 'END_BREAK'
    DeviceAuthMode authMode = DeviceAuthMode.face,
    double? similarityScore,
    String? cardNo,
    DateTime? timestamp,
  }) {
    final now = timestamp ?? DateTime.now();
    final effectiveScore = similarityScore ?? 99.2;
    final effectiveCardNo = cardNo ?? device.serialNumber ?? '88392001';
    final serialNo = now.millisecondsSinceEpoch ~/ 1000;

    final rawPayload = generateRawMachinePayload(
      protocol: device.protocol,
      employeeId: employeeId,
      employeeName: employeeName,
      punchType: punchType,
      authMode: authMode,
      timestamp: now,
      similarityScore: effectiveScore,
      cardNo: effectiveCardNo,
      serialNo: serialNo,
    );

    return TerminalAttendanceEvent(
      eventId: 'ACS_${device.id}_${now.millisecondsSinceEpoch}',
      deviceId: device.id,
      employeeId: employeeId,
      employeeName: employeeName,
      timestamp: now,
      punchType: punchType,
      authMode: authMode,
      cardNo: authMode == DeviceAuthMode.card ? effectiveCardNo : null,
      similarityScore: authMode == DeviceAuthMode.face ? effectiveScore : null,
      rawPayload: rawPayload,
    );
  }

  /// Generates the raw protocol payload matching physical device firmware specifications.
  static String generateRawMachinePayload({
    required TerminalProtocol protocol,
    required String employeeId,
    required String employeeName,
    required String punchType,
    required DeviceAuthMode authMode,
    required DateTime timestamp,
    double similarityScore = 99.2,
    String? cardNo,
    int? serialNo,
  }) {
    final serial = serialNo ?? (timestamp.millisecondsSinceEpoch ~/ 1000);

    if (protocol == TerminalProtocol.zkTecoAdms) {
      // ZKTeco ADMS Tab-Delimited Stream Format
      final zkVendorStatus = _mapPunchTypeToZkStatus(punchType);
      final zkVendorVerify = _mapAuthModeToZkVerify(authMode);
      final timeFormatted =
          '${timestamp.year}-${timestamp.month.toString().padLeft(2, '0')}-${timestamp.day.toString().padLeft(2, '0')} '
          '${timestamp.hour.toString().padLeft(2, '0')}:${timestamp.minute.toString().padLeft(2, '0')}:${timestamp.second.toString().padLeft(2, '0')}';

      return 'USER PIN=$employeeId\tTIME=$timeFormatted\tSTATUS=$zkVendorStatus\tVERIFY=$zkVendorVerify\tWORKCODE=0\tSIMILARITY=$similarityScore';
    }

    // Default: Hikvision MinMoe ISAPI JSON Schema
    final isapiAttendanceStatus = _mapPunchTypeToHikStatus(punchType);
    final isapiMinorCode = _mapAuthModeToHikMinor(authMode);
    final isapiAuthModeNum = _mapAuthModeToHikAuthModeNum(authMode);
    final isoTime = timestamp.toIso8601String();

    final payloadMap = {
      'major': 5, // Access Control Event
      'minor': isapiMinorCode, // 75=Face, 76=Finger, 1=Card, 34=PIN
      'time': isoTime,
      'employeeNoString': employeeId,
      'name': employeeName,
      'cardNo': cardNo ?? '88392001',
      'cardType': 1,
      'authMode': isapiAuthModeNum,
      'attendanceStatus': isapiAttendanceStatus,
      'similarity': similarityScore,
      'mask': 1,
      'temperature': 36.5,
      'serialNo': serial,
      'userType': 'normal',
      'currentVerifyMode': authMode.name,
      'deviceStatus': 'authenticated',
    };

    return jsonEncode(payloadMap);
  }

  static int _mapPunchTypeToHikStatus(String punchType) {
    switch (punchType.toUpperCase()) {
      case 'PUNCH_IN':
        return 0; // Check In
      case 'PUNCH_OUT':
        return 1; // Check Out
      case 'START_BREAK':
        return 2; // Break Out
      case 'END_BREAK':
        return 3; // Break In
      default:
        return 0;
    }
  }

  static int _mapPunchTypeToZkStatus(String punchType) {
    switch (punchType.toUpperCase()) {
      case 'PUNCH_IN':
        return 0;
      case 'PUNCH_OUT':
        return 1;
      case 'START_BREAK':
        return 4;
      case 'END_BREAK':
        return 5;
      default:
        return 0;
    }
  }

  static int _mapAuthModeToHikMinor(DeviceAuthMode mode) {
    switch (mode) {
      case DeviceAuthMode.face:
        return 75; // Face Authentication Passed
      case DeviceAuthMode.fingerprint:
        return 76; // Fingerprint Authentication Passed
      case DeviceAuthMode.card:
        return 1; // Card Authentication Passed
      case DeviceAuthMode.pin:
        return 34; // PIN Authentication Passed
      case DeviceAuthMode.multiModal:
        return 75;
    }
  }

  static int _mapAuthModeToHikAuthModeNum(DeviceAuthMode mode) {
    switch (mode) {
      case DeviceAuthMode.face:
        return 15;
      case DeviceAuthMode.fingerprint:
        return 17;
      case DeviceAuthMode.card:
        return 1;
      case DeviceAuthMode.pin:
        return 2;
      case DeviceAuthMode.multiModal:
        return 15;
    }
  }

  static int _mapAuthModeToZkVerify(DeviceAuthMode mode) {
    switch (mode) {
      case DeviceAuthMode.face:
        return 15;
      case DeviceAuthMode.fingerprint:
        return 1;
      case DeviceAuthMode.card:
        return 4;
      case DeviceAuthMode.pin:
        return 0;
      case DeviceAuthMode.multiModal:
        return 15;
    }
  }
}
