// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cx-015ZNc0PQW_Zdfu81a3rRmpf_peE',
    appId: '1:774828276191:web:0566ded9f0deaf995cec6a',
    messagingSenderId: '774828276191',
    projectId: 'officebiometric-e15fd',
    authDomain: 'officebiometric-e15fd.firebaseapp.com',
    storageBucket: 'officebiometric-e15fd.firebasestorage.app',
    measurementId: 'G-BEMB9KZQ8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMGVn19w3KTIbzJwOnUpT-EV_jASmwAYE',
    appId: '1:774828276191:android:8967dde9623717ef5cec6a',
    messagingSenderId: '774828276191',
    projectId: 'officebiometric-e15fd',
    storageBucket: 'officebiometric-e15fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwhouZ80R1tJMkVPDKFd-f4F5aqeOBeyA',
    appId: '1:774828276191:ios:f2db734aeea7d5295cec6a',
    messagingSenderId: '774828276191',
    projectId: 'officebiometric-e15fd',
    storageBucket: 'officebiometric-e15fd.firebasestorage.app',
    iosClientId: '774828276191-e5l10i28neh0ovo3vh9pus4rb2irtgg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybiometricApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwhouZ80R1tJMkVPDKFd-f4F5aqeOBeyA',
    appId: '1:774828276191:ios:f2db734aeea7d5295cec6a',
    messagingSenderId: '774828276191',
    projectId: 'officebiometric-e15fd',
    storageBucket: 'officebiometric-e15fd.firebasestorage.app',
    iosClientId: '774828276191-e5l10i28neh0ovo3vh9pus4rb2irtgg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybiometricApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0cx-015ZNc0PQW_Zdfu81a3rRmpf_peE',
    appId: '1:774828276191:web:8b267902b25ec1105cec6a',
    messagingSenderId: '774828276191',
    projectId: 'officebiometric-e15fd',
    authDomain: 'officebiometric-e15fd.firebaseapp.com',
    storageBucket: 'officebiometric-e15fd.firebasestorage.app',
    measurementId: 'G-FJSLPF3L9N',
  );
}
