import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Posture states of foldable dual-screen hardware devices (Pixel Fold, Galaxy Fold).
enum FoldablePosture {
  closedSingleScreen,  // Compact outer cover screen (393 x 852)
  tabletopHalfFolded,  // 90-degree laptop / tabletop mode (800 x 600 split)
  expandedDualScreen,  // 180-degree fully unfolded tablet view (1024 x 768)
}

/// Diagnostic report generated by [AqilFoldableAngleAuditor.auditFoldablePostureMatrix].
class FoldablePostureReport {
  final List<FoldablePosture> posturesTested;
  final bool hadOverflows;
  final List<String> overflowErrors;
  final DateTime auditedAt;

  FoldablePostureReport({
    required this.posturesTested,
    required this.hadOverflows,
    required this.overflowErrors,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isPostureResilient => !hadOverflows;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v10 Foldable Posture & Angle Continuity Audit');
    buf.writeln('- **Foldable Posture Status**: ${isPostureResilient ? "✅ RESILIENT ACROSS POSTURES" : "⚠️ POSTURE OVERFLOW DETECTED"}');
    buf.writeln('- **Postures Tested**: ${posturesTested.map((p) => p.name).join(', ')}');
    buf.writeln('- **Layout Overflows**: ${overflowErrors.length}');
    if (overflowErrors.isNotEmpty) {
      buf.writeln();
      buf.writeln('**Overflow Diagnostics**:');
      for (final err in overflowErrors) {
        buf.writeln('- $err');
      }
    }
    return buf.toString();
  }
}

/// AQIL v10 Frontier 4: Dynamic Device Orientation & Foldable Angle Transition Continuity Auditor.
///
/// Drives continuous geometry changes across cover screen, 90-degree tabletop,
/// and 180-degree unfolded tablet views to guarantee responsive posture continuity.
abstract final class AqilFoldableAngleAuditor {
  static const Map<FoldablePosture, Size> _postureSizes = {
    FoldablePosture.closedSingleScreen: Size(393, 852),
    FoldablePosture.tabletopHalfFolded: Size(800, 600),
    FoldablePosture.expandedDualScreen: Size(1024, 768),
  };

  /// Audits a responsive widget across closed, tabletop, and expanded foldable postures.
  static Future<FoldablePostureReport> auditFoldablePostureMatrix(
    WidgetTester tester, {
    required Widget Function(BuildContext context) builder,
  }) async {
    final tested = <FoldablePosture>[];
    final overflows = <String>[];

    for (final posture in FoldablePosture.values) {
      tested.add(posture);
      final size = _postureSizes[posture]!;

      tester.view.physicalSize = Size(size.width * 2.0, size.height * 2.0);
      tester.view.devicePixelRatio = 2.0;

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Builder(builder: builder),
          ),
        ),
      );
      await tester.pumpAndSettle();

      final dynamic exception = tester.takeException();
      if (exception != null) {
        final msg = exception.toString();
        if (msg.contains('overflowed') || msg.contains('RenderFlex')) {
          overflows.add('[$posture]: $msg');
        }
      }
    }

    // Reset view
    tester.view.resetPhysicalSize();
    tester.view.resetDevicePixelRatio();

    return FoldablePostureReport(
      posturesTested: tested,
      hadOverflows: overflows.isNotEmpty,
      overflowErrors: overflows,
    );
  }
}
