/// Complexity estimation for a discovered screen widget.
enum ScreenComplexity {
  simple,    // Single view, low widget count
  moderate,  // Standard list/form view with inputs
  complex,   // Heavy dashboard with multiple slivers, charts, or stream builders
}

/// Metadata representation of a discovered screen widget in any Antigravity project.
class DiscoveredScreen {
  final String screenName;
  final String filePath;
  final bool hasConstConstructor;
  final bool hasRequiredParams;
  final List<String> requiredParams;
  final ScreenComplexity complexity;

  const DiscoveredScreen({
    required this.screenName,
    required this.filePath,
    required this.hasConstConstructor,
    this.hasRequiredParams = false,
    this.requiredParams = const [],
    this.complexity = ScreenComplexity.moderate,
  });

  bool get isInstantiableWithoutMocks => !hasRequiredParams;

  @override
  String toString() => '$screenName ($filePath) [${complexity.name}]';
}

/// Comprehensive report generated by [AqilProjectCrawler.scanDirectoryOrSources].
class CrawlerScanReport {
  final int filesScanned;
  final List<DiscoveredScreen> screens;
  final DateTime scannedAt;

  CrawlerScanReport({
    required this.filesScanned,
    required this.screens,
    DateTime? scannedAt,
  }) : scannedAt = scannedAt ?? DateTime.now();

  int get instantiableCount => screens.where((s) => s.isInstantiableWithoutMocks).length;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v9 Project Screen Crawler Report');
    buf.writeln('- **Files Scanned**: $filesScanned');
    buf.writeln('- **Screens Discovered**: ${screens.length}');
    buf.writeln('- **Zero-Boilerplate Instantiable**: $instantiableCount');
    buf.writeln();

    if (screens.isNotEmpty) {
      buf.writeln('| Screen Name | File Path | Complexity | Const Ctor | Auto-Testable |');
      buf.writeln('| :--- | :--- | :--- | :--- | :--- |');
      for (final s in screens) {
        final autoStr = s.isInstantiableWithoutMocks ? '✅ Ready' : '⚙️ Needs Params';
        buf.writeln('| `${s.screenName}` | `${s.filePath}` | ${s.complexity.name} | ${s.hasConstConstructor} | $autoStr |');
      }
    }
    return buf.toString();
  }
}

/// AQIL v9 Frontier 1: Zero-Config Project Crawler & Auto-Suite Generator.
///
/// Discovers all Widget classes across any project (`myBiometric`, `PowerNewsApp`, etc.)
/// and autonomously generates complete multi-viewport AQIL test suites.
abstract final class AqilProjectCrawler {
  /// Scans a Dart source code string and extracts discovered Flutter `Widget` classes.
  static List<DiscoveredScreen> parseDartSource(String sourceCode, {String filePath = ''}) {
    final screens = <DiscoveredScreen>[];

    // Regex to match class declarations extending StatelessWidget or StatefulWidget
    final classRegex = RegExp(
      r'class\s+([A-Za-z0-9_]+)\s+extends\s+(StatelessWidget|StatefulWidget)',
      multiLine: true,
    );

    for (final match in classRegex.allMatches(sourceCode)) {
      final className = match.group(1);
      if (className == null || className.startsWith('_')) {
        // Skip private widgets
        continue;
      }

      // Check constructor patterns
      final constCtorRegex = RegExp('const\\s+$className\\s*\\(');
      final hasConst = constCtorRegex.hasMatch(sourceCode);

      // Check for required constructor parameters: e.g. required this.userId
      final ctorPattern = RegExp('$className\\s*\\(([^)]*)\\)');
      final ctorMatch = ctorPattern.firstMatch(sourceCode);
      final requiredParams = <String>[];

      if (ctorMatch != null) {
        final paramsStr = ctorMatch.group(1) ?? '';
        final reqRegex = RegExp(r'required\s+(?:this\.)?([A-Za-z0-9_]+)');
        for (final p in reqRegex.allMatches(paramsStr)) {
          final paramName = p.group(1);
          if (paramName != null && paramName != 'key') {
            requiredParams.add(paramName);
          }
        }
      }

      // Estimate complexity based on source characteristics
      ScreenComplexity complexity = ScreenComplexity.simple;
      if (sourceCode.contains('CustomScrollView') ||
          sourceCode.contains('StreamBuilder') ||
          sourceCode.contains('TabBarView') ||
          sourceCode.contains('Charts') ||
          sourceCode.length > 5000) {
        complexity = ScreenComplexity.complex;
      } else if (sourceCode.contains('ListView') ||
                 sourceCode.contains('TextField') ||
                 sourceCode.length > 1500) {
        complexity = ScreenComplexity.moderate;
      }

      screens.add(DiscoveredScreen(
        screenName: className,
        filePath: filePath,
        hasConstConstructor: hasConst,
        hasRequiredParams: requiredParams.isNotEmpty,
        requiredParams: requiredParams,
        complexity: complexity,
      ));
    }

    return screens;
  }

  /// Generates executable Dart code for an automated AQIL quality test file for a screen.
  static String generateTestSuiteForScreen(DiscoveredScreen screen, {String importPath = ''}) {
    final buf = StringBuffer();
    buf.writeln("// Auto-generated by AQIL v9 Project Crawler");
    buf.writeln("// Screen: ${screen.screenName}");
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln("import 'package:flutter_test/flutter_test.dart';");
    buf.writeln("import 'helpers/ui_test_helper.dart';");
    if (importPath.isNotEmpty) {
      buf.writeln("import '$importPath';");
    }
    buf.writeln();
    buf.writeln("void main() {");
    buf.writeln("  group('AQIL v9 Fleet Suite — ${screen.screenName}', () {");
    buf.writeln("    testWidgets('passes multi-viewport AQIL quality matrix', (WidgetTester tester) async {");

    if (screen.isInstantiableWithoutMocks) {
      final instantiation = screen.hasConstConstructor ? 'const ${screen.screenName}()' : '${screen.screenName}()';
      buf.writeln("      final scorecard = await UiQualityTester.runFullAqilSuite(");
      buf.writeln("        tester,");
      buf.writeln("        componentName: '${screen.screenName}',");
      buf.writeln("        builder: (context) => $instantiation,");
      buf.writeln("      );");
      buf.writeln("      expect(scorecard.complianceScore, greaterThanOrEqualTo(85.0));");
    } else {
      buf.writeln("      // Note: ${screen.screenName} requires parameters: ${screen.requiredParams.join(', ')}");
      buf.writeln("      // Provide test mocks or fixtures to instantiate.");
    }

    buf.writeln("    });");
    buf.writeln("  });");
    buf.writeln("}");
    return buf.toString();
  }
}
