import 'dart:convert';
import 'dart:math' as math;
import 'package:flutter/material.dart';

/// Supported W3C Design Tokens Community Group (DTCG) specification token types.
enum W3cTokenType {
  color,
  dimension,
  duration,
  cubicBezier,
  fontFamily,
  fontWeight,
  fontSize,
  number,
  unknown;

  static W3cTokenType fromString(String? typeStr) {
    if (typeStr == null) return W3cTokenType.unknown;
    switch (typeStr.toLowerCase()) {
      case 'color':
        return W3cTokenType.color;
      case 'dimension':
      case 'size':
      case 'spacing':
      case 'radius':
        return W3cTokenType.dimension;
      case 'duration':
      case 'time':
        return W3cTokenType.duration;
      case 'cubicbezier':
      case 'easing':
        return W3cTokenType.cubicBezier;
      case 'fontfamily':
        return W3cTokenType.fontFamily;
      case 'fontweight':
        return W3cTokenType.fontWeight;
      case 'fontsize':
        return W3cTokenType.fontSize;
      case 'number':
        return W3cTokenType.number;
      default:
        return W3cTokenType.unknown;
    }
  }
}

/// A parsed token node adhering to W3C Design Tokens Community Group (DTCG) format.
class W3cDesignToken {
  final String path;
  final dynamic rawValue;
  final W3cTokenType type;
  final String? description;

  const W3cDesignToken({
    required this.path,
    required this.rawValue,
    required this.type,
    this.description,
  });

  /// Resolves numeric dimension in dp / px.
  double? get dimensionValue {
    if (rawValue is num) return (rawValue as num).toDouble();
    if (rawValue is String) {
      final clean = (rawValue as String).replaceAll(RegExp(r'[a-zA-Z%]'), '').trim();
      return double.tryParse(clean);
    }
    return null;
  }

  /// Resolves standard 32-bit ARGB hex color integer.
  int? get colorArgbValue {
    if (rawValue is int) return rawValue as int;
    if (rawValue is String) {
      String hex = (rawValue as String).replaceAll('#', '').trim();
      if (hex.length == 6) hex = 'FF$hex';
      if (hex.length == 8) return int.tryParse(hex, radix: 16);
    }
    return null;
  }

  /// Resolves duration in milliseconds.
  int? get durationMsValue {
    if (rawValue is num) return (rawValue as num).toInt();
    if (rawValue is String) {
      final s = rawValue as String;
      if (s.endsWith('ms')) {
        return int.tryParse(s.replaceAll('ms', '').trim());
      } else if (s.endsWith('s')) {
        final seconds = double.tryParse(s.replaceAll('s', '').trim());
        return seconds != null ? (seconds * 1000).toInt() : null;
      }
      return int.tryParse(s.trim());
    }
    return null;
  }

  Map<String, dynamic> toW3cJson() => {
    r'$value': rawValue,
    r'$type': type.name,
    if (description != null) r'$description': description,
  };
}

/// Nature of design token divergence between authoritative Figma spec and Flutter.
enum TokenDriftType {
  synchronized,
  valueDrift,
  missingInFlutter,
  missingInFigma,
  typeMismatch,
}

/// Individual item violation or divergence detected during token drift audit.
class TokenDriftItem {
  final String tokenPath;
  final String tokenType;
  final TokenDriftType driftType;
  final dynamic figmaValue;
  final dynamic flutterValue;
  final double? numericVariance;
  final String message;

  const TokenDriftItem({
    required this.tokenPath,
    required this.tokenType,
    required this.driftType,
    this.figmaValue,
    this.flutterValue,
    this.numericVariance,
    required this.message,
  });

  @override
  String toString() => '[$driftType] $tokenPath: $message';
}

/// Comprehensive report generated by [AqilFigmaTokenSentinel.auditTokenDrift].
class FigmaTokenDriftReport {
  final int totalFigmaTokens;
  final int totalFlutterTokens;
  final int syncedTokens;
  final List<TokenDriftItem> drifts;
  final double syncScore;
  final DateTime auditedAt;

  FigmaTokenDriftReport({
    required this.totalFigmaTokens,
    required this.totalFlutterTokens,
    required this.syncedTokens,
    required this.drifts,
    required this.syncScore,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isCompliant => drifts.isEmpty;
  bool get hasDrift => drifts.isNotEmpty;

  /// Generates a ready-to-apply Dart patch to update Flutter token classes.
  String generateFlutterSyncPatch() {
    if (drifts.isEmpty) return '// All Flutter tokens are in 100% sync with Figma DTCG spec.';

    final buf = StringBuffer();
    buf.writeln('// AQIL v7 Figma Token Drift Sync Patch');
    buf.writeln('// Generated: ${auditedAt.toIso8601String()}');
    buf.writeln('// Apply these corrections to align with authoritative Figma DTCG specs:\n');

    for (final d in drifts) {
      if (d.driftType == TokenDriftType.valueDrift || d.driftType == TokenDriftType.missingInFlutter) {
        buf.writeln('// Token: ${d.tokenPath} (${d.tokenType})');
        buf.writeln('// Reason: ${d.message}');
        if (d.tokenType == 'color' && d.figmaValue != null) {
          final hex = d.figmaValue.toString().replaceAll('#', '').toUpperCase();
          final fullHex = hex.length == 6 ? 'FF$hex' : hex;
          buf.writeln('static const Color ${d.tokenPath.split('.').last} = Color(0x$fullHex);');
        } else if (d.tokenType == 'dimension' && d.figmaValue != null) {
          final val = d.figmaValue is num ? (d.figmaValue as num).toDouble() : d.figmaValue;
          buf.writeln('static const double ${d.tokenPath.split('.').last} = $val;');
        } else if (d.tokenType == 'duration' && d.figmaValue != null) {
          buf.writeln('static const Duration ${d.tokenPath.split('.').last} = Duration(milliseconds: ${d.figmaValue});');
        }
        buf.writeln();
      }
    }
    return buf.toString();
  }

  /// Generates a two-way JSON patch to update Figma Tokens Studio with Flutter additions.
  Map<String, dynamic> generateFigmaTokensPatch() {
    final patch = <String, dynamic>{};
    for (final d in drifts) {
      if (d.driftType == TokenDriftType.missingInFigma && d.flutterValue != null) {
        final segments = d.tokenPath.split('.');
        Map<String, dynamic> current = patch;
        for (var i = 0; i < segments.length - 1; i++) {
          current = current.putIfAbsent(segments[i], () => <String, dynamic>{}) as Map<String, dynamic>;
        }
        current[segments.last] = {
          r'$value': d.flutterValue,
          r'$type': d.tokenType,
          r'$description': 'Auto-synced from Flutter codebase token',
        };
      }
    }
    return patch;
  }

  /// Markdown audit summary table for PR checks and design review.
  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v7 Figma Token Drift Audit');
    buf.writeln('- **Status**: ${isCompliant ? "✅ 100% IN SYNC" : "⚠️ DRIFT DETECTED"}');
    buf.writeln('- **Sync Score**: ${syncScore.toStringAsFixed(1)}%');
    buf.writeln('- **Figma Tokens Scanned**: $totalFigmaTokens');
    buf.writeln('- **Flutter Tokens Scanned**: $totalFlutterTokens');
    buf.writeln('- **Drifts / Discrepancies**: ${drifts.length}');
    buf.writeln();

    if (drifts.isNotEmpty) {
      buf.writeln('| Token Path | Type | Drift Category | Figma Spec | Flutter Code | Remediation |');
      buf.writeln('| :--- | :--- | :--- | :--- | :--- | :--- |');
      for (final d in drifts) {
        buf.writeln('| `${d.tokenPath}` | ${d.tokenType} | ${d.driftType.name} | `${d.figmaValue ?? "N/A"}` | `${d.flutterValue ?? "N/A"}` | ${d.message} |');
      }
    }
    return buf.toString();
  }
}

/// AQIL v7 Frontier 5: Figma Two-Way Design Token Drift Sentinel.
///
/// Implements full bidirectional verification between authoritative Figma Design
/// Tokens (W3C DTCG specification) and Flutter design system token repositories.
abstract final class AqilFigmaTokenSentinel {
  /// Recursively parses a nested W3C DTCG JSON object into a flat map of [W3cDesignToken].
  static Map<String, W3cDesignToken> parseW3cTokens(Map<String, dynamic> json, [String prefix = '']) {
    final result = <String, W3cDesignToken>{};

    for (final entry in json.entries) {
      final key = entry.key;
      final val = entry.value;

      if (key.startsWith(r'$') && key != r'$value') {
        continue;
      }

      final currentPath = prefix.isEmpty ? key : '$prefix.$key';

      if (val is Map<String, dynamic>) {
        if (val.containsKey(r'$value')) {
          // This is a leaf design token
          final typeStr = val[r'$type'] as String?;
          final type = typeStr != null ? W3cTokenType.fromString(typeStr) : _inferTypeFromPath(currentPath);
          final desc = val[r'$description'] as String?;
          result[currentPath] = W3cDesignToken(
            path: currentPath,
            rawValue: val[r'$value'],
            type: type,
            description: desc,
          );
        } else {
          // Nested group
          result.addAll(parseW3cTokens(val, currentPath));
        }
      } else {
        // Flat leaf format fallback: e.g. "spacing.md": 12
        final type = _inferTypeFromPath(currentPath);
        result[currentPath] = W3cDesignToken(
          path: currentPath,
          rawValue: val,
          type: type,
        );
      }
    }

    return result;
  }

  static W3cTokenType _inferTypeFromPath(String path) {
    final lower = path.toLowerCase();
    if (lower.contains('color') || lower.contains('palette') || lower.contains('bg') || lower.contains('fg')) {
      return W3cTokenType.color;
    }
    if (lower.contains('space') || lower.contains('spacing') || lower.contains('gap') || lower.contains('margin') || lower.contains('padding')) {
      return W3cTokenType.dimension;
    }
    if (lower.contains('radius') || lower.contains('corner') || lower.contains('size') || lower.contains('target')) {
      return W3cTokenType.dimension;
    }
    if (lower.contains('duration') || lower.contains('motion') || lower.contains('animation')) {
      return W3cTokenType.duration;
    }
    if (lower.contains('font') || lower.contains('text')) {
      return W3cTokenType.fontSize;
    }
    return W3cTokenType.dimension;
  }

  /// Audits token drift between Figma W3C tokens and Flutter design tokens.
  ///
  /// [figmaTokensJson]: authoritative W3C Design Tokens JSON map.
  /// [flutterTokens]: key-value map of Flutter design system values (Color, double, int, Duration).
  /// [dimensionTolerancePx]: allowed tolerance in dp (default 0.5dp).
  static FigmaTokenDriftReport auditTokenDrift({
    required Map<String, dynamic> figmaTokensJson,
    required Map<String, dynamic> flutterTokens,
    double dimensionTolerancePx = 0.5,
  }) {
    final parsedFigma = parseW3cTokens(figmaTokensJson);
    final drifts = <TokenDriftItem>[];
    int syncedCount = 0;

    // 1. Audit Figma tokens against Flutter implementations
    for (final entry in parsedFigma.entries) {
      final path = entry.key;
      final figmaToken = entry.value;

      // Look up in Flutter tokens by direct path or normalized key
      final flutterVal = _lookupFlutterToken(flutterTokens, path);

      if (flutterVal == null) {
        drifts.add(TokenDriftItem(
          tokenPath: path,
          tokenType: figmaToken.type.name,
          driftType: TokenDriftType.missingInFlutter,
          figmaValue: figmaToken.rawValue,
          message: 'Token defined in Figma W3C spec but missing from Flutter codebase',
        ));
        continue;
      }

      // Check type and value matching
      final matchResult = _compareTokenValues(
        figmaToken: figmaToken,
        flutterValue: flutterVal,
        dimensionTolerancePx: dimensionTolerancePx,
      );

      if (matchResult == null) {
        syncedCount++;
      } else {
        drifts.add(matchResult);
      }
    }

    // 2. Audit Flutter tokens for orphaned tokens (missing in Figma spec)
    for (final flutterKey in flutterTokens.keys) {
      final figmaMatch = _lookupFigmaToken(parsedFigma, flutterKey);
      if (figmaMatch == null) {
        drifts.add(TokenDriftItem(
          tokenPath: flutterKey,
          tokenType: _inferFlutterType(flutterTokens[flutterKey]),
          driftType: TokenDriftType.missingInFigma,
          flutterValue: flutterTokens[flutterKey],
          message: 'Token declared in Flutter codebase but not found in Figma authoritative spec',
        ));
      }
    }

    final totalExpected = math.max(parsedFigma.length, 1);
    final score = math.max(0.0, ((totalExpected - drifts.length) / totalExpected) * 100.0);

    return FigmaTokenDriftReport(
      totalFigmaTokens: parsedFigma.length,
      totalFlutterTokens: flutterTokens.length,
      syncedTokens: syncedCount,
      drifts: drifts,
      syncScore: score.clamp(0.0, 100.0),
    );
  }

  static dynamic _lookupFlutterToken(Map<String, dynamic> flutterTokens, String figmaPath) {
    if (flutterTokens.containsKey(figmaPath)) return flutterTokens[figmaPath];

    // Try last segment e.g. "spacing.md" -> "md" or "spacingMd"
    final segments = figmaPath.split('.');
    final last = segments.last;
    if (flutterTokens.containsKey(last)) return flutterTokens[last];

    // Try camelCase combination: e.g. "spacing.md" -> "spacingMd"
    if (segments.length >= 2) {
      final camel = segments.first + segments.sublist(1).map((s) => s.isNotEmpty ? s[0].toUpperCase() + s.substring(1) : s).join('');
      if (flutterTokens.containsKey(camel)) return flutterTokens[camel];
    }

    return null;
  }

  static W3cDesignToken? _lookupFigmaToken(Map<String, W3cDesignToken> parsedFigma, String flutterKey) {
    if (parsedFigma.containsKey(flutterKey)) return parsedFigma[flutterKey];

    // Match suffix or partial path
    for (final entry in parsedFigma.entries) {
      if (entry.key.endsWith('.$flutterKey') || entry.key == flutterKey) {
        return entry.value;
      }
      // Check camelCase matching
      final segments = entry.key.split('.');
      if (segments.length >= 2) {
        final camel = segments.first + segments.sublist(1).map((s) => s.isNotEmpty ? s[0].toUpperCase() + s.substring(1) : s).join('');
        if (camel == flutterKey) return entry.value;
      }
    }
    return null;
  }

  static String _inferFlutterType(dynamic val) {
    if (val is Color) return 'color';
    if (val is Duration) return 'duration';
    if (val is num) return 'dimension';
    return 'unknown';
  }

  static TokenDriftItem? _compareTokenValues({
    required W3cDesignToken figmaToken,
    required dynamic flutterValue,
    required double dimensionTolerancePx,
  }) {
    if (figmaToken.type == W3cTokenType.color) {
      final expectedArgb = figmaToken.colorArgbValue;
      int? actualArgb;
      if (flutterValue is Color) {
        actualArgb = flutterValue.toARGB32();
      } else if (flutterValue is int) {
        actualArgb = flutterValue;
      } else if (flutterValue is String) {
        String hex = flutterValue.replaceAll('#', '').trim();
        if (hex.length == 6) hex = 'FF$hex';
        actualArgb = int.tryParse(hex, radix: 16);
      }

      if (expectedArgb == null || actualArgb == null || expectedArgb != actualArgb) {
        return TokenDriftItem(
          tokenPath: figmaToken.path,
          tokenType: 'color',
          driftType: TokenDriftType.valueDrift,
          figmaValue: figmaToken.rawValue,
          flutterValue: flutterValue is Color ? '#${flutterValue.toARGB32().toRadixString(16).padLeft(8, '0').toUpperCase()}' : flutterValue,
          message: 'Color value mismatch: Figma 0x${expectedArgb?.toRadixString(16).toUpperCase()} != Flutter 0x${actualArgb?.toRadixString(16).toUpperCase()}',
        );
      }
    } else if (figmaToken.type == W3cTokenType.dimension || figmaToken.type == W3cTokenType.number || figmaToken.type == W3cTokenType.fontSize) {
      final expectedNum = figmaToken.dimensionValue;
      double? actualNum;
      if (flutterValue is num) {
        actualNum = flutterValue.toDouble();
      } else if (flutterValue is String) {
        actualNum = double.tryParse(flutterValue.replaceAll(RegExp(r'[a-zA-Z%]'), '').trim());
      }

      if (expectedNum == null || actualNum == null) {
        return TokenDriftItem(
          tokenPath: figmaToken.path,
          tokenType: 'dimension',
          driftType: TokenDriftType.typeMismatch,
          figmaValue: figmaToken.rawValue,
          flutterValue: flutterValue,
          message: 'Unable to parse dimension values for comparison',
        );
      }

      final diff = (expectedNum - actualNum).abs();
      if (diff > dimensionTolerancePx) {
        return TokenDriftItem(
          tokenPath: figmaToken.path,
          tokenType: 'dimension',
          driftType: TokenDriftType.valueDrift,
          figmaValue: expectedNum,
          flutterValue: actualNum,
          numericVariance: diff,
          message: 'Dimension variance ${diff.toStringAsFixed(2)}dp exceeds tolerance ${dimensionTolerancePx}dp (Figma: ${expectedNum}dp, Flutter: ${actualNum}dp)',
        );
      }
    } else if (figmaToken.type == W3cTokenType.duration) {
      final expectedMs = figmaToken.durationMsValue;
      int? actualMs;
      if (flutterValue is Duration) {
        actualMs = flutterValue.inMilliseconds;
      } else if (flutterValue is num) {
        actualMs = flutterValue.toInt();
      }

      if (expectedMs != actualMs) {
        return TokenDriftItem(
          tokenPath: figmaToken.path,
          tokenType: 'duration',
          driftType: TokenDriftType.valueDrift,
          figmaValue: expectedMs,
          flutterValue: actualMs,
          message: 'Motion duration mismatch: Figma ${expectedMs}ms != Flutter ${actualMs}ms',
        );
      }
    }

    return null; // Synchronized!
  }

  /// Exports a standard Flutter tokens dictionary into W3C DTCG specification JSON.
  static String exportW3cJson(Map<String, dynamic> flutterTokens) {
    final root = <String, dynamic>{};
    for (final entry in flutterTokens.entries) {
      final key = entry.key;
      final val = entry.value;
      final segments = key.split('.');

      Map<String, dynamic> curr = root;
      for (var i = 0; i < segments.length - 1; i++) {
        curr = curr.putIfAbsent(segments[i], () => <String, dynamic>{}) as Map<String, dynamic>;
      }

      dynamic exportValue;
      String exportType;
      if (val is Color) {
        exportValue = '#${val.toARGB32().toRadixString(16).padLeft(8, '0').toUpperCase()}';
        exportType = 'color';
      } else if (val is Duration) {
        exportValue = '${val.inMilliseconds}ms';
        exportType = 'duration';
      } else if (val is num) {
        exportValue = val;
        exportType = 'dimension';
      } else {
        exportValue = val.toString();
        exportType = 'dimension';
      }

      curr[segments.last] = {
        r'$value': exportValue,
        r'$type': exportType,
      };
    }

    return const JsonEncoder.withIndent('  ').convert(root);
  }
}
