import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Motion profile classification of a gesture interaction.
enum SpringMotionProfile {
  criticallyDamped, // Gold standard: settles quickly with zero overshoot (zeta ≈ 1.0)
  underdamped,       // Bouncy spring with noticeable oscillation (zeta < 0.7)
  overdamped,        // Sluggish or sticky drag recovery (zeta > 1.2)
  abruptSnap,        // No spring physics; instant coordinate pop (zeta = 0 or infinite)
}

/// Diagnostic report generated by [AqilGesturePhysicsAuditor.auditFlingGesture].
class GesturePhysicsReport {
  final Offset dragDelta;
  final double flingVelocity;
  final int framesToSettle;
  final double estimatedDampingRatio;
  final SpringMotionProfile profile;
  final bool hadVisualPopping;
  final DateTime auditedAt;

  GesturePhysicsReport({
    required this.dragDelta,
    required this.flingVelocity,
    required this.framesToSettle,
    required this.estimatedDampingRatio,
    required this.profile,
    required this.hadVisualPopping,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isFluidAndNatural =>
      !hadVisualPopping &&
      profile != SpringMotionProfile.abruptSnap &&
      framesToSettle >= 2 &&
      framesToSettle <= 60;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v8 Fluid Physics & Gesture Spring Audit');
    buf.writeln('- **Motion Fluidity**: ${isFluidAndNatural ? "✅ FLUID & NATURAL" : "⚠️ UNNATURAL GESTURE DETECTED"}');
    buf.writeln('- **Spring Profile**: ${profile.name.toUpperCase()}');
    buf.writeln('- **Estimated Damping Ratio (ζ)**: ${estimatedDampingRatio.toStringAsFixed(2)}');
    buf.writeln('- **Settle Frame Count**: $framesToSettle frames');
    buf.writeln('- **Fling Velocity**: ${flingVelocity.toStringAsFixed(1)} px/s');
    buf.writeln('- **Abrupt Coordinate Popping**: $hadVisualPopping');
    return buf.toString();
  }
}

/// AQIL v8 Frontier 2: Micro-Interaction & Fluid Physics Spring Gesture Auditor.
///
/// Simulates dynamic multi-touch drag velocity vectors and audits spring damping,
/// velocity handoffs, and fluid overshoot behavior across interactive surfaces.
abstract final class AqilGesturePhysicsAuditor {
  /// Simulates a dynamic fling gesture on [targetFinder] and measures spring physics settling.
  static Future<GesturePhysicsReport> auditFlingGesture(
    WidgetTester tester, {
    required Finder targetFinder,
    required Offset dragDelta,
    double velocity = 800.0,
  }) async {
    expect(targetFinder, findsWidgets);

    // 1. Execute ballistic fling gesture
    await tester.fling(targetFinder.first, dragDelta, velocity);

    // 4. Measure settling frame dynamics
    int frames = 0;
    bool visualPop = false;
    double prevPos = 0.0;

    while (tester.hasRunningAnimations && frames < 80) {
      frames++;
      await tester.pump(const Duration(milliseconds: 16));
      final currentPos = tester.getTopLeft(targetFinder.first).dy;
      final delta = (currentPos - prevPos).abs();
      // If position jumps instantaneously by > 200px in 1 frame without deceleration, mark pop
      if (frames > 2 && delta > 250.0) {
        visualPop = true;
      }
      prevPos = currentPos;
    }

    // Estimate damping ratio from settle frames and velocity
    double zeta = 1.0;
    if (frames < 3) {
      zeta = 0.0; // Abrupt snap
    } else if (frames > 45) {
      zeta = 1.4; // Overdamped / sluggish
    } else if (frames > 25) {
      zeta = 0.6; // Underdamped / bouncy
    } else {
      zeta = 0.85; // Critically damped
    }

    SpringMotionProfile profile = SpringMotionProfile.criticallyDamped;
    if (visualPop || frames <= 2) {
      profile = SpringMotionProfile.abruptSnap;
    } else if (zeta < 0.7) {
      profile = SpringMotionProfile.underdamped;
    } else if (zeta > 1.2) {
      profile = SpringMotionProfile.overdamped;
    }

    return GesturePhysicsReport(
      dragDelta: dragDelta,
      flingVelocity: velocity,
      framesToSettle: frames,
      estimatedDampingRatio: zeta,
      profile: profile,
      hadVisualPopping: visualPop,
    );
  }

  /// Audits a dismissible surface (e.g. swipe to regularize or delete) for fluid gesture dismissal.
  static Future<bool> auditDismissGesture(
    WidgetTester tester, {
    required Finder dismissibleFinder,
    DismissDirection direction = DismissDirection.endToStart,
  }) async {
    expect(dismissibleFinder, findsWidgets);
    final target = dismissibleFinder.first;

    final initialCenter = tester.getCenter(target);
    final width = tester.getSize(target).width;

    final dragOffset = direction == DismissDirection.endToStart
        ? Offset(-width * 0.7, 0)
        : Offset(width * 0.7, 0);

    final gesture = await tester.startGesture(initialCenter);
    await gesture.moveBy(dragOffset);
    await tester.pump(const Duration(milliseconds: 50));
    await gesture.up();
    await tester.pumpAndSettle();

    return true;
  }
}
