import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Category of adversarial data mutation.
enum MutationCategory {
  extremeStringLength,
  zeroWidthCharacters,
  complexCompositeEmoji,
  negativeNumericBoundary,
  malformedUrlPath,
  scriptInjectionPayload,
  emptyCollection,
}

/// A specific adversarial test vector injected into UI components.
class MutationVector {
  final String name;
  final dynamic payload;
  final MutationCategory category;

  const MutationVector({
    required this.name,
    required this.payload,
    required this.category,
  });

  /// Standard enterprise adversarial corpus for Flutter widget fuzzing.
  static final List<MutationVector> defaultCorpus = [
    MutationVector(
      name: '10,000-Char Super-String',
      payload: 'EnterpriseWorkforce ' * 500,
      category: MutationCategory.extremeStringLength,
    ),
    const MutationVector(
      name: 'Zero-Width Invisible Space',
      payload: 'Arun\u200B\u200C\u200D\uFEFFKumar',
      category: MutationCategory.zeroWidthCharacters,
    ),
    const MutationVector(
      name: 'Multi-Person Complex Emoji',
      payload: '👨‍👩‍👧‍👦 👩🏾‍🚀 🏳️‍⚧️ 🧟‍♀️',
      category: MutationCategory.complexCompositeEmoji,
    ),
    const MutationVector(
      name: 'Extreme Negative Number',
      payload: -999999.99,
      category: MutationCategory.negativeNumericBoundary,
    ),
    const MutationVector(
      name: 'Broken Image Remote URL',
      payload: 'https://127.0.0.1:9999/non_existent_avatar.png',
      category: MutationCategory.malformedUrlPath,
    ),
    const MutationVector(
      name: 'Script & Tag Payload',
      payload: '<script>alert("pwned")</script>',
      category: MutationCategory.scriptInjectionPayload,
    ),
  ];
}

/// Result of an individual mutation fuzzing trial.
class MutationTrialResult {
  final String vectorName;
  final MutationCategory category;
  final bool survivedWithoutCrash;
  final bool renderedValidBox;
  final String? exceptionDetail;

  const MutationTrialResult({
    required this.vectorName,
    required this.category,
    required this.survivedWithoutCrash,
    required this.renderedValidBox,
    this.exceptionDetail,
  });

  bool get isClean => survivedWithoutCrash && renderedValidBox;
}

/// Diagnostic report generated by [AqilMutationResilienceEngine.auditResilience].
class MutationResilienceReport {
  final int totalTrials;
  final int survivedTrials;
  final double crashResistanceIndex; // 0 to 100
  final List<MutationTrialResult> trialResults;
  final DateTime auditedAt;

  MutationResilienceReport({
    required this.totalTrials,
    required this.survivedTrials,
    required this.crashResistanceIndex,
    required this.trialResults,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isCrashProof => crashResistanceIndex >= 95.0;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v8 Adversarial Mutation Resilience Audit');
    buf.writeln('- **Resilience Status**: ${isCrashProof ? "✅ CRASH-PROOF & ADVERSARIALLY RESILIENT" : "⚠️ VULNERABLE TO DATA MUTATION"}');
    buf.writeln('- **Crash Resistance Index (CRI)**: ${crashResistanceIndex.toStringAsFixed(1)} / 100');
    buf.writeln('- **Trials Survived**: $survivedTrials / $totalTrials');
    buf.writeln();

    buf.writeln('| Vector | Category | Survived | Valid RenderBox | Details |');
    buf.writeln('| :--- | :--- | :--- | :--- | :--- |');
    for (final t in trialResults) {
      final passStr = t.isClean ? '✅ PASS' : '❌ FAIL';
      buf.writeln('| `${t.vectorName}` | ${t.category.name} | ${t.survivedWithoutCrash} | ${t.renderedValidBox} | $passStr |');
    }
    return buf.toString();
  }
}

/// AQIL v8 Frontier 6: Autonomous Adversarial Mutation Resilience Engine.
///
/// Injects boundary mutation vectors (10k strings, zero-width chars, complex emojis,
/// broken image URLs) and evaluates Crash Resistance Index (CRI).
abstract final class AqilMutationResilienceEngine {
  /// Audits widget resilience against boundary mutation vectors.
  static Future<MutationResilienceReport> auditResilience(
    WidgetTester tester, {
    required Widget Function(BuildContext context, dynamic mutatedValue) builder,
    List<MutationVector>? corpus,
  }) async {
    final vectors = corpus ?? MutationVector.defaultCorpus;
    final results = <MutationTrialResult>[];
    int survivedCount = 0;

    for (final vec in vectors) {
      bool survived = true;
      bool validBox = true;
      String? exception;

      try {
        await tester.pumpWidget(
          MaterialApp(
            home: Scaffold(
              body: Builder(
                builder: (context) => builder(context, vec.payload),
              ),
            ),
          ),
        );
        await tester.pump();

        final dynamic caught = tester.takeException();
        if (caught != null) {
          survived = false;
          exception = caught.toString();
        } else {
          // Check if any RenderBox crashed to zero or unbounded
          final boxes = tester.renderObjectList<RenderBox>(find.byType(Builder));
          if (boxes.isEmpty) {
            validBox = false;
          }
        }
      } catch (e) {
        survived = false;
        exception = e.toString();
      }

      if (survived && validBox) {
        survivedCount++;
      }

      results.add(MutationTrialResult(
        vectorName: vec.name,
        category: vec.category,
        survivedWithoutCrash: survived,
        renderedValidBox: validBox,
        exceptionDetail: exception,
      ));
    }

    final total = vectors.isNotEmpty ? vectors.length : 1;
    final cri = (survivedCount / total) * 100.0;

    return MutationResilienceReport(
      totalTrials: vectors.length,
      survivedTrials: survivedCount,
      crashResistanceIndex: cri,
      trialResults: results,
    );
  }
}
