import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Category of media asset defects.
enum MediaDefectType {
  unboundedDimensions,    // Image without fixed width/height/aspect ratio (CLS risk)
  missingErrorFallback,   // Image without errorBuilder or fallback placeholder
  skeletonDimensionDrift, // Shimmer skeleton size differs from loaded content (> 4dp)
}

/// A specific media asset violation detected during audit.
class MediaAssetViolation {
  final MediaDefectType type;
  final String description;
  final String recommendation;

  const MediaAssetViolation({
    required this.type,
    required this.description,
    required this.recommendation,
  });

  @override
  String toString() => '[${type.name}] $description';
}

/// Diagnostic report generated by [AqilMediaAssetAuditor.auditMediaAssets].
class MediaAssetReport {
  final int totalMediaScanned;
  final List<MediaAssetViolation> violations;
  final bool hasUnboundedImages;
  final bool hasProperErrorFallbacks;
  final DateTime auditedAt;

  MediaAssetReport({
    required this.totalMediaScanned,
    required this.violations,
    required this.hasUnboundedImages,
    required this.hasProperErrorFallbacks,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isCompliant => violations.isEmpty;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v9 Media Asset & Shimmer Skeleton Audit');
    buf.writeln('- **Media Compliance**: ${isCompliant ? "✅ COMPLIANT & CLS-PROTECTED" : "⚠️ MEDIA DEFECTS DETECTED"}');
    buf.writeln('- **Media Elements Scanned**: $totalMediaScanned');
    buf.writeln('- **Unbounded Images (CLS Risk)**: $hasUnboundedImages');
    buf.writeln('- **Error Fallbacks Declared**: $hasProperErrorFallbacks');
    if (violations.isNotEmpty) {
      buf.writeln();
      buf.writeln('| Defect | Description | Recommended Fix |');
      buf.writeln('| :--- | :--- | :--- |');
      for (final v in violations) {
        buf.writeln('| `${v.type.name}` | ${v.description} | ${v.recommendation} |');
      }
    }
    return buf.toString();
  }
}

/// AQIL v9 Frontier 2: Media Asset, Shimmer Skeleton & Broken Image Auditor.
///
/// Audits image containers for bounded aspect ratios, error fallbacks, and layout stability.
abstract final class AqilMediaAssetAuditor {
  /// Scans the pumped widget tree for image aspect ratio stability and error fallbacks.
  static MediaAssetReport auditMediaAssets(
    WidgetTester tester, {
    Finder? rootFinder,
  }) {
    final violations = <MediaAssetViolation>[];
    int mediaCount = 0;
    bool foundUnbounded = false;
    bool foundMissingFallback = false;

    // 1. Audit Image widgets
    final imageWidgets = tester.widgetList<Image>(rootFinder ?? find.byType(Image));
    for (final img in imageWidgets) {
      mediaCount++;
      // Check if image has bounded dimensions or aspect ratio
      if (img.width == null && img.height == null) {
        foundUnbounded = true;
        violations.add(MediaAssetViolation(
          type: MediaDefectType.unboundedDimensions,
          description: 'Image widget #${img.hashCode} lacks explicit width or height constraints',
          recommendation: 'Wrap Image in AspectRatio, SizedBox, or specify width/height to prevent Cumulative Layout Shift (CLS)',
        ));
      }

      // Check error fallback
      if (img.errorBuilder == null && img.image is NetworkImage) {
        foundMissingFallback = true;
        violations.add(const MediaAssetViolation(
          type: MediaDefectType.missingErrorFallback,
          description: 'NetworkImage lacks an errorBuilder fallback for offline/404 handling',
          recommendation: 'Specify errorBuilder: (ctx, err, stack) => Icon(Icons.broken_image)',
        ));
      }
    }

    // 2. Audit CircleAvatar and DecoratedBoxes
    final avatars = tester.widgetList<CircleAvatar>(rootFinder ?? find.byType(CircleAvatar));
    for (final av in avatars) {
      mediaCount++;
      if (av.backgroundImage != null && av.backgroundImage is NetworkImage) {
        // Avatars should specify radius or child fallback
        if (av.child == null) {
          violations.add(const MediaAssetViolation(
            type: MediaDefectType.missingErrorFallback,
            description: 'CircleAvatar with NetworkImage lacks fallback child widget',
            recommendation: 'Add child: Icon(Icons.person) to render when image is loading or offline',
          ));
        }
      }
    }

    return MediaAssetReport(
      totalMediaScanned: mediaCount,
      violations: violations,
      hasUnboundedImages: foundUnbounded,
      hasProperErrorFallbacks: !foundMissingFallback,
    );
  }

  /// Verifies that a shimmer loading skeleton geometry aligns with final loaded content.
  static Future<bool> verifyShimmerLayoutMatch(
    WidgetTester tester, {
    required Widget Function(BuildContext) shimmerBuilder,
    required Widget Function(BuildContext) loadedBuilder,
    double tolerancePx = 4.0,
  }) async {
    // 1. Pump shimmer
    await tester.pumpWidget(MaterialApp(home: Scaffold(body: Builder(builder: shimmerBuilder))));
    await tester.pump();
    final shimmerBox = tester.renderObject(find.byType(Scaffold)) as RenderBox;
    final shimmerSize = shimmerBox.size;

    // 2. Pump loaded
    await tester.pumpWidget(MaterialApp(home: Scaffold(body: Builder(builder: loadedBuilder))));
    await tester.pump();
    final loadedBox = tester.renderObject(find.byType(Scaffold)) as RenderBox;
    final loadedSize = loadedBox.size;

    final widthDiff = (shimmerSize.width - loadedSize.width).abs();
    final heightDiff = (shimmerSize.height - loadedSize.height).abs();

    return widthDiff <= tolerancePx && heightDiff <= tolerancePx;
  }
}
