import 'dart:convert';
import 'package:crypto/crypto.dart';

/// An immutable offline attendance record block linked cryptographically in a hash chain.
class OfflinePunchBlock {
  final int index;
  final String employeeId;
  final DateTime timestamp;
  final String punchType;
  final String previousHash;
  final String blockHash;

  const OfflinePunchBlock({
    required this.index,
    required this.employeeId,
    required this.timestamp,
    required this.punchType,
    required this.previousHash,
    required this.blockHash,
  });

  Map<String, dynamic> toJson() => {
    'index': index,
    'employeeId': employeeId,
    'timestamp': timestamp.toIso8601String(),
    'punchType': punchType,
    'previousHash': previousHash,
    'blockHash': blockHash,
  };
}

/// Diagnostic report generated by [AqilHashChainSentinel.verifyChainIntegrity].
class HashChainReport {
  final int totalBlocks;
  final bool isChainIntact;
  final List<int> corruptedIndices;
  final DateTime auditedAt;

  HashChainReport({
    required this.totalBlocks,
    required this.isChainIntact,
    required this.corruptedIndices,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v10 Cryptographic Hash-Chain Integrity Audit');
    buf.writeln('- **Chain Status**: ${isChainIntact ? "✅ CRYPTOGRAPHICALLY SECURE & TAMPER-PROOF" : "⚠️ CHAIN TAMPERING DETECTED"}');
    buf.writeln('- **Total Verified Blocks**: $totalBlocks');
    buf.writeln('- **Tampered / Corrupted Blocks**: ${corruptedIndices.length}');
    if (corruptedIndices.isNotEmpty) {
      buf.writeln('- **Compromised Indices**: ${corruptedIndices.join(', ')}');
    }
    return buf.toString();
  }
}

/// AQIL v10 Frontier 5: Cryptographic Integrity & Offline Punch Hash-Chain Sentinel.
///
/// Implements deterministic SHA-256 hash-chaining to audit offline logs against
/// local tampering, out-of-order clock injection, and signature corruption.
abstract final class AqilHashChainSentinel {
  /// Computes a deterministic SHA-256 block hash.
  static String computeHash({
    required int index,
    required String employeeId,
    required DateTime timestamp,
    required String punchType,
    required String previousHash,
  }) {
    final raw = '$index|$employeeId|${timestamp.toIso8601String()}|$punchType|$previousHash';
    return sha256.convert(utf8.encode(raw)).toString();
  }

  /// Creates a new signed block in an existing chain.
  static OfflinePunchBlock createBlock({
    required int index,
    required String employeeId,
    required DateTime timestamp,
    required String punchType,
    required String previousHash,
  }) {
    final hash = computeHash(
      index: index,
      employeeId: employeeId,
      timestamp: timestamp,
      punchType: punchType,
      previousHash: previousHash,
    );

    return OfflinePunchBlock(
      index: index,
      employeeId: employeeId,
      timestamp: timestamp,
      punchType: punchType,
      previousHash: previousHash,
      blockHash: hash,
    );
  }

  /// Verifies complete cryptographic integrity across an offline punch sequence.
  static HashChainReport verifyChainIntegrity(List<OfflinePunchBlock> blocks) {
    if (blocks.isEmpty) {
      return HashChainReport(totalBlocks: 0, isChainIntact: true, corruptedIndices: []);
    }

    final corrupted = <int>[];
    String expectedPrev = 'GENESIS_BLOCK_ROOT';

    for (var i = 0; i < blocks.length; i++) {
      final b = blocks[i];

      // 1. Verify previous hash link
      if (b.previousHash != expectedPrev) {
        corrupted.add(i);
      }

      // 2. Recompute hash
      final actual = computeHash(
        index: b.index,
        employeeId: b.employeeId,
        timestamp: b.timestamp,
        punchType: b.punchType,
        previousHash: b.previousHash,
      );

      if (actual != b.blockHash) {
        corrupted.add(i);
      }

      expectedPrev = b.blockHash;
    }

    return HashChainReport(
      totalBlocks: blocks.length,
      isChainIntact: corrupted.isEmpty,
      corruptedIndices: corrupted.toSet().toList()..sort(),
    );
  }
}
