import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Configuration options for synthetic pseudo-localization.
class PseudoLocConfig {
  final double expansionRatio;
  final bool replaceWithAccents;
  final bool insertBidiMarkers;
  final bool wrapDelimiters;

  const PseudoLocConfig({
    this.expansionRatio = 0.40, // +40% length expansion
    this.replaceWithAccents = true,
    this.insertBidiMarkers = false,
    this.wrapDelimiters = true,
  });

  static const standard = PseudoLocConfig();
  static const aggressive = PseudoLocConfig(expansionRatio: 0.60, insertBidiMarkers: true);
}

/// Diagnostic report generated by [AqilPseudoLocEngine.auditPseudoLocalization].
class PseudoLocReport {
  final int stringsTransformed;
  final int detectedOverflows;
  final List<String> flaggedElements;
  final double expansionFactor;
  final bool isReflowResilient;
  final DateTime auditedAt;

  PseudoLocReport({
    required this.stringsTransformed,
    required this.detectedOverflows,
    required this.flaggedElements,
    required this.expansionFactor,
    required this.isReflowResilient,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v8 Pseudo-Localization & Length Expansion Audit');
    buf.writeln('- **Reflow Status**: ${isReflowResilient ? "✅ REFLOW RESILIENT" : "⚠️ LOCALIZATION OVERFLOW DETECTED"}');
    buf.writeln('- **Expansion Factor**: +${(expansionFactor * 100).toStringAsFixed(0)}% length increase');
    buf.writeln('- **Strings Transformed**: $stringsTransformed');
    buf.writeln('- **Layout Overflows**: $detectedOverflows');
    if (flaggedElements.isNotEmpty) {
      buf.writeln();
      buf.writeln('**Clipped / Overflowing Localized Elements**:');
      for (final el in flaggedElements) {
        buf.writeln('- $el');
      }
    }
    return buf.toString();
  }
}

/// AQIL v8 Frontier 5: Autonomous Pseudo-Localization & BiDi Length Expansion Reflow Simulator.
///
/// Automatically expands text strings by +40% with accented unicode glyphs to stress-test
/// widget layouts, chips, buttons, and table headers against international translation reflow.
abstract final class AqilPseudoLocEngine {
  static const Map<String, String> _accentMap = {
    'a': 'à', 'b': 'ƀ', 'c': 'ç', 'd': 'ð', 'e': 'é', 'f': 'ƒ', 'g': 'ĝ',
    'h': 'ĥ', 'i': 'î', 'j': 'ĵ', 'k': 'ķ', 'l': 'ļ', 'm': 'ɱ', 'n': 'ñ',
    'o': 'ö', 'p': 'þ', 'q': 'ǫ', 'r': 'ŕ', 's': 'š', 't': 'ţ', 'u': 'û',
    'v': 'ṽ', 'w': 'ŵ', 'x': 'ẋ', 'y': 'ý', 'z': 'ž',
    'A': 'À', 'B': 'Ɓ', 'C': 'Ç', 'D': 'Ð', 'E': 'É', 'F': 'Ƒ', 'G': 'Ĝ',
    'H': 'Ĥ', 'I': 'Î', 'J': 'Ĵ', 'K': 'Ķ', 'L': 'Ļ', 'M': 'Ṁ', 'N': 'Ñ',
    'O': 'Ö', 'P': 'Þ', 'Q': 'Ǫ', 'R': 'Ŕ', 'S': 'Š', 'T': 'Ţ', 'U': 'Û',
    'V': 'Ṽ', 'W': 'Ŵ', 'X': 'Ẋ', 'Y': 'Ý', 'Z': 'Ž',
  };

  /// Transforms plain text into expanded pseudo-localized text.
  static String pseudoLocalize(String input, [PseudoLocConfig config = PseudoLocConfig.standard]) {
    if (input.trim().isEmpty) return input;

    final buf = StringBuffer();
    if (config.wrapDelimiters) buf.write('[!!! ');

    for (final char in input.split('')) {
      if (config.replaceWithAccents && _accentMap.containsKey(char)) {
        buf.write(_accentMap[char]);
      } else {
        buf.write(char);
      }
    }

    // Append length expansion characters (e.g. +40%)
    final extraChars = (input.length * config.expansionRatio).round();
    if (extraChars > 0) {
      buf.write(' ');
      buf.write('ñé'.padRight(extraChars, 'ö').substring(0, extraChars));
    }

    if (config.wrapDelimiters) buf.write(' !!!]');
    return buf.toString();
  }

  /// Audits a responsive widget tree under pseudo-localized expansion stress.
  static Future<PseudoLocReport> auditPseudoLocalization(
    WidgetTester tester, {
    required Widget Function(BuildContext context, String Function(String) l10n) builder,
    PseudoLocConfig config = PseudoLocConfig.standard,
    Size viewport = const Size(393, 852),
  }) async {
    int transformedCount = 0;
    String l10nMock(String raw) {
      transformedCount++;
      return pseudoLocalize(raw, config);
    }

    tester.view.physicalSize = Size(viewport.width * 2.0, viewport.height * 2.0);
    tester.view.devicePixelRatio = 2.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Builder(
            builder: (context) => builder(context, l10nMock),
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    final dynamic exception = tester.takeException();
    final overflows = <String>[];
    if (exception != null) {
      final msg = exception.toString();
      if (msg.contains('overflowed') || msg.contains('RenderFlex')) {
        overflows.add(msg);
      }
    }

    return PseudoLocReport(
      stringsTransformed: transformedCount,
      detectedOverflows: overflows.length,
      flaggedElements: overflows,
      expansionFactor: config.expansionRatio,
      isReflowResilient: overflows.isEmpty,
    );
  }
}
