import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Diagnostic report generated by [AqilA11yGoldenBaseline.compareSnapshots].
class A11yBaselineDiffReport {
  final int totalBaselineNodes;
  final int totalCurrentNodes;
  final bool isMatchingBaseline;
  final List<String> semanticDiffs;
  final DateTime auditedAt;

  A11yBaselineDiffReport({
    required this.totalBaselineNodes,
    required this.totalCurrentNodes,
    required this.isMatchingBaseline,
    required this.semanticDiffs,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v10 Accessibility Tree Golden Baseline Audit');
    buf.writeln('- **Baseline Parity**: ${isMatchingBaseline ? "✅ 100% MATCH (ZERO REGRESSION)" : "⚠️ ACCESSIBILITY REGRESSION DETECTED"}');
    buf.writeln('- **Baseline Nodes**: $totalBaselineNodes');
    buf.writeln('- **Current Nodes**: $totalCurrentNodes');
    buf.writeln('- **Semantic Regressions**: ${semanticDiffs.length}');
    if (semanticDiffs.isNotEmpty) {
      buf.writeln();
      buf.writeln('**Detected Semantic Diffs**:');
      for (final diff in semanticDiffs) {
        buf.writeln('- $diff');
      }
    }
    return buf.toString();
  }
}

/// AQIL v10 Frontier 6: Autonomous Cross-Platform Accessibility Tree Golden Baseline.
///
/// Captures deterministic snapshots of the Semantics tree and diff-checks PRs
/// to prevent silent drops of screen reader labels or button flags.
abstract final class AqilA11yGoldenBaseline {
  /// Captures a normalized textual snapshot of the current semantics tree.
  static List<String> captureSemanticLabels(WidgetTester tester, {Finder? rootFinder}) {
    final semanticsHandles = <String>[];
    final rootElement = tester.element(rootFinder ?? find.byType(MaterialApp).first);

    void traverseRenderObject(RenderObject obj) {
      final sem = obj.debugSemantics;
      if (sem != null) {
        final label = sem.label;
        final isBtn = sem.flagsCollection.isButton;
        final isHdr = sem.flagsCollection.isHeader;
        if (label.isNotEmpty) {
          final flags = [
            if (isBtn) 'BUTTON',
            if (isHdr) 'HEADER',
          ].join(',');
          semanticsHandles.add('$label ${flags.isNotEmpty ? "[$flags]" : ""}');
        }
      }
      obj.visitChildren(traverseRenderObject);
    }

    final renderObj = rootElement.renderObject;
    if (renderObj != null) {
      traverseRenderObject(renderObj);
    }

    return semanticsHandles;
  }

  /// Compares current semantics labels against an authoritative baseline list.
  static A11yBaselineDiffReport compareSnapshots({
    required List<String> baseline,
    required List<String> current,
  }) {
    final diffs = <String>[];

    for (final baseLabel in baseline) {
      if (!current.contains(baseLabel)) {
        diffs.add('Missing baseline semantic element: "$baseLabel"');
      }
    }

    for (final currLabel in current) {
      if (!baseline.contains(currLabel)) {
        diffs.add('New unexpected semantic element: "$currLabel"');
      }
    }

    return A11yBaselineDiffReport(
      totalBaselineNodes: baseline.length,
      totalCurrentNodes: current.length,
      isMatchingBaseline: diffs.isEmpty,
      semanticDiffs: diffs,
    );
  }
}
