import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Perceptual spatial density classification of a UI screen or component.
enum SpatialDensity {
  cramped,  // Insufficient breathing room (< 8dp margins, high clutter)
  compact,  // High information density suitable for data tables/kiosks (8-12dp)
  balanced, // Goldilocks enterprise standard (16-24dp rhythm, 8pt grid harmony)
  airy,     // Generous spacing (24-40dp), ideal for onboarding and modals
  sparse,   // Excessive dead space or disproportionate gap voids (> 64dp empty space)
}

/// Category of spatial or visual tension detected by [AqilSpatialTensionAuditor].
enum SpatialTensionType {
  gridMisalignment,       // Element dimensions or padding not aligned to 4pt/8pt grid
  asymmetricPadding,      // Accidental left/right or top/bottom divergence
  crampedCardPadding,     // Container padding < 8dp with dense content
  muddyTypographyScale,   // Heading vs body font scale ratio < 1.15x with identical weight
  excessiveDeadSpace,     // Spacers or flex voids pushing content awkwardly
}

/// Details of a single spatial tension violation.
class SpatialTensionViolation {
  final SpatialTensionType type;
  final String elementDescription;
  final String details;
  final double severity; // 0.0 to 1.0

  const SpatialTensionViolation({
    required this.type,
    required this.elementDescription,
    required this.details,
    this.severity = 0.5,
  });

  @override
  String toString() => '[${type.name}] $elementDescription: $details';
}

/// Diagnostic report generated by [AqilSpatialTensionAuditor.auditSpatialTension].
class SpatialTensionReport {
  final double tensionScore;
  final double gridHarmonyRatio;
  final SpatialDensity density;
  final int totalNodesScanned;
  final List<SpatialTensionViolation> violations;
  final double typographyScaleHarmonic;
  final DateTime auditedAt;

  SpatialTensionReport({
    required this.tensionScore,
    required this.gridHarmonyRatio,
    required this.density,
    required this.totalNodesScanned,
    required this.violations,
    required this.typographyScaleHarmonic,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isHarmonious => tensionScore >= 80.0 && violations.where((v) => v.severity > 0.7).isEmpty;

  int get criticalViolationsCount => violations.where((v) => v.severity >= 0.7).length;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v7 Visual Layout & Spatial Tension Audit');
    buf.writeln('- **Aesthetic Status**: ${isHarmonious ? "✅ HARMONIOUS & BALANCED" : "⚠️ SPATIAL TENSION FLAGGED"}');
    buf.writeln('- **Spatial Harmony Score**: ${tensionScore.toStringAsFixed(1)} / 100');
    buf.writeln('- **8pt Grid Alignment**: ${(gridHarmonyRatio * 100).toStringAsFixed(1)}%');
    buf.writeln('- **Density Classification**: ${density.name.toUpperCase()}');
    buf.writeln('- **Typography Scale Harmonic**: ${typographyScaleHarmonic.toStringAsFixed(2)}x');
    buf.writeln('- **Elements Evaluated**: $totalNodesScanned');
    buf.writeln('- **Spatial Tension Violations**: ${violations.length} ($criticalViolationsCount critical)');
    buf.writeln();

    if (violations.isNotEmpty) {
      buf.writeln('| Type | Element | Severity | Diagnostic & Remediation |');
      buf.writeln('| :--- | :--- | :--- | :--- |');
      for (final v in violations) {
        final sevStr = v.severity >= 0.7 ? '🔴 HIGH' : (v.severity >= 0.4 ? '🟡 MED' : '🔵 LOW');
        buf.writeln('| `${v.type.name}` | ${v.elementDescription} | $sevStr | ${v.details} |');
      }
    }
    return buf.toString();
  }
}

/// AQIL v7 Frontier 6: Multimodal Visual Layout & Spatial Tension Auditor.
///
/// Autonomously inspects Flutter render trees and widget layouts to measure
/// visual harmony, padding symmetry, 8pt grid adherence, and typography hierarchy contrast.
abstract final class AqilSpatialTensionAuditor {
  /// Audits the currently pumped widget tree for spatial tension and layout rhythm.
  static SpatialTensionReport auditSpatialTension(
    WidgetTester tester, {
    Finder? rootFinder,
    double gridBaseline = 4.0,
  }) {
    final violations = <SpatialTensionViolation>[];
    int nodesScanned = 0;
    int gridAlignedCount = 0;
    int gridCheckedCount = 0;

    // 1. Audit Padding & Inset symmetry and grid alignment
    final paddingWidgets = tester.widgetList<Padding>(rootFinder ?? find.byType(Padding));
    for (final p in paddingWidgets) {
      nodesScanned++;
      final insets = p.padding;
      if (insets is EdgeInsets) {
        gridCheckedCount += 4;
        if (insets.left % gridBaseline == 0) gridAlignedCount++;
        if (insets.right % gridBaseline == 0) gridAlignedCount++;
        if (insets.top % gridBaseline == 0) gridAlignedCount++;
        if (insets.bottom % gridBaseline == 0) gridAlignedCount++;

        // Asymmetric horizontal padding detection (unbalanced gutter drift)
        final hDiff = (insets.left - insets.right).abs();
        if (hDiff > 4.0 && insets.left > 0 && insets.right > 0) {
          violations.add(SpatialTensionViolation(
            type: SpatialTensionType.asymmetricPadding,
            elementDescription: 'Padding [left: ${insets.left}, right: ${insets.right}]',
            details: 'Horizontal padding divergence of ${hDiff.toStringAsFixed(1)}dp causes visual balance skew',
            severity: hDiff > 12.0 ? 0.75 : 0.4,
          ));
        }

        // Extremely tight padding with non-zero values
        if ((insets.left > 0 && insets.left < 4.0) ||
            (insets.right > 0 && insets.right < 4.0) ||
            (insets.top > 0 && insets.top < 4.0) ||
            (insets.bottom > 0 && insets.bottom < 4.0)) {
          violations.add(SpatialTensionViolation(
            type: SpatialTensionType.crampedCardPadding,
            elementDescription: 'Sub-4dp Padding',
            details: 'Padding insets < 4dp ($insets) create cramped border claustrophobia',
            severity: 0.6,
          ));
        }
      }
    }

    // 2. Audit Card / Container surfaces for cramped padding
    final cardFinders = find.byType(Card);
    for (final cardElement in cardFinders.evaluate()) {
      nodesScanned++;
      final renderBox = cardElement.renderObject as RenderBox?;
      if (renderBox != null && renderBox.hasSize) {
        final size = renderBox.size;
        gridCheckedCount += 2;
        if (size.width % gridBaseline == 0) gridAlignedCount++;
        if (size.height % gridBaseline == 0) gridAlignedCount++;
      }
    }

    // 3. Audit Typography Hierarchy Scale (Contrast between Title & Body)
    final textWidgets = tester.widgetList<Text>(rootFinder ?? find.byType(Text)).toList();
    nodesScanned += textWidgets.length;
    double maxFontSize = 0.0;
    double minFontSize = 999.0;
    final fontSizes = <double>[];

    for (final t in textWidgets) {
      final style = t.style;
      final size = style?.fontSize ?? 14.0;
      fontSizes.add(size);
      if (size > maxFontSize) maxFontSize = size;
      if (size < minFontSize) minFontSize = size;
    }

    double typographyScaleRatio = 1.0;
    if (fontSizes.length >= 2 && minFontSize > 0 && minFontSize < 900) {
      fontSizes.sort();
      // Compare adjacent distinct font sizes
      final distinctSizes = fontSizes.toSet().toList()..sort();
      for (var i = 0; i < distinctSizes.length - 1; i++) {
        final lower = distinctSizes[i];
        final higher = distinctSizes[i + 1];
        final stepRatio = higher / lower;
        if (stepRatio < 1.12 && higher >= 14.0) {
          violations.add(SpatialTensionViolation(
            type: SpatialTensionType.muddyTypographyScale,
            elementDescription: 'Adjacent Text (${lower}sp vs ${higher}sp)',
            details: 'Typography step scale ratio is only ${stepRatio.toStringAsFixed(2)}x (< 1.15x minimum hierarchy contrast)',
            severity: 0.5,
          ));
        }
      }
      typographyScaleRatio = maxFontSize / math.max(minFontSize, 1.0);
    }

    // 4. Audit Flex / Spacers for Excessive Dead Space
    final sizedBoxes = tester.widgetList<SizedBox>(rootFinder ?? find.byType(SizedBox));
    for (final sb in sizedBoxes) {
      nodesScanned++;
      if (sb.height != null) {
        final h = sb.height!;
        gridCheckedCount++;
        if (h % gridBaseline == 0) gridAlignedCount++;

        if (h >= 80.0) {
          violations.add(SpatialTensionViolation(
            type: SpatialTensionType.excessiveDeadSpace,
            elementDescription: 'SizedBox(height: ${h.toStringAsFixed(0)}dp)',
            details: 'Excessive spacer height (${h.toStringAsFixed(0)}dp) introduces dead void space and wastes viewport budget',
            severity: h > 120.0 ? 0.7 : 0.45,
          ));
        }
      }
      if (sb.width != null) {
        final w = sb.width!;
        gridCheckedCount++;
        if (w % gridBaseline == 0) gridAlignedCount++;
      }
    }

    // Calculate Grid Harmony Ratio
    final gridHarmony = gridCheckedCount > 0 ? (gridAlignedCount / gridCheckedCount) : 1.0;

    // Density Classification
    SpatialDensity density = SpatialDensity.balanced;
    if (violations.any((v) => v.type == SpatialTensionType.crampedCardPadding)) {
      density = SpatialDensity.cramped;
    } else if (violations.any((v) => v.type == SpatialTensionType.excessiveDeadSpace)) {
      density = SpatialDensity.sparse;
    } else if (gridHarmony > 0.85 && violations.isEmpty) {
      density = SpatialDensity.balanced;
    }

    // Overall Score Calculation (0 to 100)
    double penalty = 0.0;
    for (final v in violations) {
      penalty += v.severity * 12.0;
    }
    final rawScore = 100.0 - penalty - ((1.0 - gridHarmony) * 20.0);
    final score = rawScore.clamp(0.0, 100.0);

    return SpatialTensionReport(
      tensionScore: score,
      gridHarmonyRatio: gridHarmony,
      density: density,
      totalNodesScanned: math.max(nodesScanned, 1),
      violations: violations,
      typographyScaleHarmonic: typographyScaleRatio,
    );
  }
}
