import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Diagnostic report generated by [AqilOledPowerAuditor.auditOledDarkProfile].
class OledPowerReport {
  final double estimatedAplPercent;
  final bool hasPureBlackSmearRisk;
  final List<String> smearRiskElements;
  final double powerEfficiencyScore;
  final bool isDarkTheme;
  final DateTime auditedAt;

  OledPowerReport({
    required this.estimatedAplPercent,
    required this.hasPureBlackSmearRisk,
    required this.smearRiskElements,
    required this.powerEfficiencyScore,
    required this.isDarkTheme,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isCompliant => !hasPureBlackSmearRisk && powerEfficiencyScore >= 75.0;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v8 OLED Power & Dark Mode Smear Audit');
    buf.writeln('- **OLED Compliance**: ${isCompliant ? "✅ OLED COMPLIANT & BATTERY EFFICIENT" : "⚠️ OLED SMEARING / POWER RISK"}');
    buf.writeln('- **Average Picture Level (APL)**: ${estimatedAplPercent.toStringAsFixed(1)}%');
    buf.writeln('- **Power Efficiency Score**: ${powerEfficiencyScore.toStringAsFixed(1)} / 100');
    buf.writeln('- **OLED Purple-Smear Risk**: ${hasPureBlackSmearRisk ? "DETECTED" : "NONE"}');
    buf.writeln('- **Theme Mode**: ${isDarkTheme ? "Dark Mode" : "Light Mode"}');
    if (smearRiskElements.isNotEmpty) {
      buf.writeln();
      buf.writeln('**Flagged Pure-Black (#000000) Scrollables**:');
      for (final el in smearRiskElements) {
        buf.writeln('- $el');
      }
    }
    return buf.toString();
  }
}

/// AQIL v8 Frontier 4: Zero-Trust OLED Power & Dark Mode Black-Smear Sentinel.
///
/// Evaluates Average Picture Level (APL) for battery consumption and detects
/// pure-black (#000000) surfaces in scrollables that cause OLED pixel turn-on smearing.
abstract final class AqilOledPowerAuditor {
  /// Audits the pumped widget tree for OLED power consumption and black smearing defects.
  static OledPowerReport auditOledDarkProfile(
    WidgetTester tester, {
    Finder? rootFinder,
  }) {
    final context = tester.element(rootFinder ?? find.byType(Scaffold).first);
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    final smearElements = <String>[];
    double totalLuminance = 0.0;
    int samples = 0;

    // 1. Audit Scaffold background color for pure-black vs M3 tonal surface
    final scaffoldBg = theme.scaffoldBackgroundColor;
    final scaffoldLuminance = scaffoldBg.computeLuminance();
    totalLuminance += scaffoldLuminance;
    samples++;

    // 2. Audit scrollable surfaces (ListView, CustomScrollView, SingleChildScrollView)
    final scrollables = find.byType(Scrollable);
    for (final s in scrollables.evaluate()) {
      final widget = s.widget as Scrollable;
      // Check surrounding container or card colors
      final parentElement = s;
      final renderBox = parentElement.renderObject as RenderBox?;
      if (renderBox != null) {
        // If background is pure black (0xFF000000) in dark mode, flag smear risk
        if (isDark && (scaffoldBg.toARGB32() == 0xFF000000)) {
          smearElements.add('Scrollable #${widget.hashCode}: pure black background (#000000) causes OLED diode turn-on latency smearing');
        }
      }
    }

    // 3. Sample Material Surfaces and Cards
    final materials = tester.widgetList<Material>(find.byType(Material));
    for (final m in materials) {
      if (m.color != null) {
        totalLuminance += m.color!.computeLuminance();
        samples++;
      }
    }

    final avgLuminance = samples > 0 ? (totalLuminance / samples) : 0.2;
    final aplPercent = (avgLuminance * 100.0).clamp(0.0, 100.0);

    // Score: For dark mode, APL between 5% and 25% is optimal (score 90-100)
    double score = 85.0;
    if (isDark) {
      if (aplPercent >= 5.0 && aplPercent <= 30.0) {
        score = 95.0;
      } else if (aplPercent > 50.0) {
        score = 65.0; // Too bright for dark mode
      }
    } else {
      score = 80.0; // Light mode baseline
    }

    if (smearElements.isNotEmpty) {
      score -= 25.0;
    }

    return OledPowerReport(
      estimatedAplPercent: aplPercent,
      hasPureBlackSmearRisk: smearElements.isNotEmpty,
      smearRiskElements: smearElements,
      powerEfficiencyScore: score.clamp(0.0, 100.0),
      isDarkTheme: isDark,
    );
  }
}
