/// Single project quality status inside the fleet dashboard.
class ProjectQualitySummary {
  final String projectName;
  final double complianceScore;
  final int totalTests;
  final double passRate;
  final String grade;
  final String primaryDomain;

  const ProjectQualitySummary({
    required this.projectName,
    required this.complianceScore,
    required this.totalTests,
    required this.passRate,
    required this.grade,
    required this.primaryDomain,
  });
}

/// Comprehensive multi-project dashboard generated by [AqilUnifiedDashboard].
class FleetDashboardReport {
  final List<ProjectQualitySummary> projects;
  final DateTime generatedAt;

  FleetDashboardReport({
    required this.projects,
    DateTime? generatedAt,
  }) : generatedAt = generatedAt ?? DateTime.now();

  double get fleetAverageScore => projects.isNotEmpty
      ? projects.map((p) => p.complianceScore).reduce((a, b) => a + b) / projects.length
      : 100.0;

  String get fleetGrade {
    final avg = fleetAverageScore;
    if (avg >= 95) return 'A+';
    if (avg >= 90) return 'A';
    if (avg >= 80) return 'B';
    return 'C';
  }

  /// Generates a standalone, beautiful HTML dashboard report.
  String generateHtmlDashboard() {
    final buf = StringBuffer();
    buf.writeln('<!DOCTYPE html>');
    buf.writeln('<html lang="en">');
    buf.writeln('<head>');
    buf.writeln('<meta charset="UTF-8">');
    buf.writeln('<title>AQIL v9 Fleet Quality Dashboard</title>');
    buf.writeln('<style>');
    buf.writeln('body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0f172a; color: #f8fafc; margin: 0; padding: 40px; }');
    buf.writeln('.container { max-width: 1000px; margin: 0 auto; }');
    buf.writeln('.header { border-bottom: 1px solid #334155; padding-bottom: 20px; margin-bottom: 30px; }');
    buf.writeln('.card { background: #1e293b; border-radius: 12px; padding: 24px; margin-bottom: 20px; border: 1px solid #334155; }');
    buf.writeln('table { width: 100%; border-collapse: collapse; margin-top: 15px; }');
    buf.writeln('th, td { text-align: left; padding: 12px; border-bottom: 1px solid #334155; }');
    buf.writeln('.badge { background: #10b981; color: white; padding: 4px 8px; border-radius: 6px; font-weight: bold; }');
    buf.writeln('</style>');
    buf.writeln('</head>');
    buf.writeln('<body>');
    buf.writeln('<div class="container">');
    buf.writeln('<div class="header">');
    buf.writeln('<h1>🏛️ AQIL v9 Cross-Project Quality Fleet</h1>');
    buf.writeln('<p>Antigravity Project Ecosystem | Generated: ${generatedAt.toIso8601String()}</p>');
    buf.writeln('</div>');
    buf.writeln('<div class="card">');
    buf.writeln('<h2>Fleet Summary: Grade <span class="badge">$fleetGrade</span> (${fleetAverageScore.toStringAsFixed(1)}%)</h2>');
    buf.writeln('<table>');
    buf.writeln('<tr><th>Project</th><th>Domain</th><th>Score</th><th>Tests</th><th>Pass Rate</th><th>Grade</th></tr>');
    for (final p in projects) {
      buf.writeln('<tr>');
      buf.writeln('<td><strong>${p.projectName}</strong></td>');
      buf.writeln('<td>${p.primaryDomain}</td>');
      buf.writeln('<td>${p.complianceScore.toStringAsFixed(1)}%</td>');
      buf.writeln('<td>${p.totalTests}</td>');
      buf.writeln('<td>${(p.passRate * 100).toStringAsFixed(0)}%</td>');
      buf.writeln('<td><span class="badge">${p.grade}</span></td>');
      buf.writeln('</tr>');
    }
    buf.writeln('</table>');
    buf.writeln('</div>');
    buf.writeln('</div>');
    buf.writeln('</body>');
    buf.writeln('</html>');
    return buf.toString();
  }

  /// Generates a standard SVG shield badge for repository README files.
  static String generateSvgBadge({
    required String label,
    required String value,
    String color = '#10b981',
  }) {
    final labelWidth = label.length * 7 + 12;
    final valueWidth = value.length * 7 + 12;
    final totalWidth = labelWidth + valueWidth;

    return '<svg xmlns="http://www.w3.org/2000/svg" width="$totalWidth" height="20">'
        '<linearGradient id="b" x2="0" y2="100%">'
        '<stop offset="0" stop-color="#bbb" stop-opacity=".1"/>'
        '<stop offset="1" stop-opacity=".1"/>'
        '</linearGradient>'
        '<clipPath id="a"><rect width="$totalWidth" height="20" rx="3" fill="#fff"/></clipPath>'
        '<g clip-path="url(#a)">'
        '<rect width="$labelWidth" height="20" fill="#555"/>'
        '<rect x="$labelWidth" width="$valueWidth" height="20" fill="$color"/>'
        '<rect width="$totalWidth" height="20" fill="url(#b)"/>'
        '</g>'
        '<g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">'
        '<text x="${labelWidth / 2}" y="15" fill="#010101" fill-opacity=".3">$label</text>'
        '<text x="${labelWidth / 2}" y="14">$label</text>'
        '<text x="${labelWidth + valueWidth / 2}" y="15" fill="#010101" fill-opacity=".3">$value</text>'
        '<text x="${labelWidth + valueWidth / 2}" y="14">$value</text>'
        '</g>'
        '</svg>';
  }
}

/// AQIL v9 Frontier 6: Cross-Project Unified Quality Dashboard & SVG Badge Generator.
///
/// Collects multi-project health summaries across `D:\Program\Antigravity` and
/// emits standalone HTML dashboards and README SVG badges.
abstract final class AqilUnifiedDashboard {
  /// Builds a sample standard Antigravity fleet summary across known projects.
  static FleetDashboardReport buildAntigravityFleetReport() {
    return FleetDashboardReport(
      projects: const [
        ProjectQualitySummary(
          projectName: 'myBiometric',
          complianceScore: 99.2,
          totalTests: 346,
          passRate: 1.0,
          grade: 'A+',
          primaryDomain: 'Biometric Kiosk & Enterprise HRMS',
        ),
        ProjectQualitySummary(
          projectName: 'PowerNewsApp',
          complianceScore: 94.5,
          totalTests: 42,
          passRate: 0.98,
          grade: 'A',
          primaryDomain: 'News & Media Publishing',
        ),
        ProjectQualitySummary(
          projectName: 'ToDo-App',
          complianceScore: 96.0,
          totalTests: 35,
          passRate: 1.0,
          grade: 'A',
          primaryDomain: 'Productivity & Task Management',
        ),
        ProjectQualitySummary(
          projectName: 'TrackMyTrip',
          complianceScore: 93.8,
          totalTests: 28,
          passRate: 0.97,
          grade: 'A',
          primaryDomain: 'GPS & Location Tracking',
        ),
        ProjectQualitySummary(
          projectName: 'Vehicle Log Book',
          complianceScore: 95.2,
          totalTests: 32,
          passRate: 1.0,
          grade: 'A',
          primaryDomain: 'Fleet & Vehicle Expense Ledger',
        ),
      ],
    );
  }
}
