import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Categories of Presentation Attacks on Biometric Sensors (ISO/IEC 30107-3 PAD Standard).
enum BiometricSpoofType {
  printedPhoto2D,         // Paper photo held in front of sensor
  digitalScreenReplay,    // Smartphone/tablet video playback
  siliconeMask3D,         // 3D latex or silicone mask
  ambientGlareOverexposed,// Extreme direct sunlight washing out sensor
  occludedFacePartial,    // Face mask, dark sunglasses, or hand covering nose
}

/// Diagnostic report generated by [AqilBiometricSpoofSentinel.auditAntiSpoofResilience].
class BiometricSpoofReport {
  final int totalAttacksTested;
  final int attacksSafelyRejected;
  final bool displayedSecurityWarning;
  final bool triggeredLockoutOrOverride;
  final double securityScore;
  final DateTime auditedAt;

  BiometricSpoofReport({
    required this.totalAttacksTested,
    required this.attacksSafelyRejected,
    required this.displayedSecurityWarning,
    required this.triggeredLockoutOrOverride,
    required this.securityScore,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isSecure => attacksSafelyRejected == totalAttacksTested && securityScore >= 85.0;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v10 Biometric Spoof & Liveness Sentinel Report');
    buf.writeln('- **Security Status**: ${isSecure ? "✅ SECURE & PAD COMPLIANT" : "⚠️ SPOOF VULNERABILITY DETECTED"}');
    buf.writeln('- **PAD Compliance Score**: ${securityScore.toStringAsFixed(1)} / 100');
    buf.writeln('- **Attacks Tested**: $totalAttacksTested');
    buf.writeln('- **Attacks Safely Rejected**: $attacksSafelyRejected');
    buf.writeln('- **Security Alert Displayed**: $displayedSecurityWarning');
    buf.writeln('- **Lockout / Supervisor Override**: $triggeredLockoutOrOverride');
    return buf.toString();
  }
}

/// AQIL v10 Frontier 2: Biometric Spoof & Liveness Sensor Attack Simulation Sentinel.
///
/// Injects simulated 2D print, digital replay, and lighting occlusion presentation attacks
/// to verify that kiosk authentication UI rejects fraudulent attempts and shows lockout UI.
abstract final class AqilBiometricSpoofSentinel {
  /// Audits anti-spoof resilience across presentation attack vectors.
  static Future<BiometricSpoofReport> auditAntiSpoofResilience(
    WidgetTester tester, {
    required Widget Function(BuildContext context, BiometricSpoofType attack) builder,
    List<BiometricSpoofType> vectors = BiometricSpoofType.values,
  }) async {
    int rejectedCount = 0;
    bool showedWarning = false;
    bool hadLockout = false;

    for (final attack in vectors) {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Builder(builder: (ctx) => builder(ctx, attack)),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // Check for security rejection indicators
      final rejected = find.textContaining(RegExp(r'spoof|rejected|failed|liveness|invalid|try again|fraud', caseSensitive: false)).evaluate().isNotEmpty ||
          find.byIcon(Icons.security).evaluate().isNotEmpty ||
          find.byIcon(Icons.error_outline).evaluate().isNotEmpty;

      if (rejected) {
        rejectedCount++;
        showedWarning = true;
      }

      // Check if fallback supervisor PIN override or lockout is offered
      if (find.textContaining(RegExp(r'pin|override|supervisor|locked', caseSensitive: false)).evaluate().isNotEmpty) {
        hadLockout = true;
      }
    }

    final total = vectors.isNotEmpty ? vectors.length : 1;
    final score = ((rejectedCount / total) * 60.0) +
        (showedWarning ? 20.0 : 0.0) +
        (hadLockout ? 20.0 : 0.0);

    return BiometricSpoofReport(
      totalAttacksTested: vectors.length,
      attacksSafelyRejected: rejectedCount,
      displayedSecurityWarning: showedWarning,
      triggeredLockoutOrOverride: hadLockout,
      securityScore: score.clamp(0.0, 100.0),
    );
  }
}
