import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Diagnostic report generated by [AqilGcThrashSentinel.auditAllocationStability].
class GcThrashReport {
  final int cyclesExecuted;
  final int initialImageCacheBytes;
  final int finalImageCacheBytes;
  final bool isMemoryStable;
  final DateTime auditedAt;

  GcThrashReport({
    required this.cyclesExecuted,
    required this.initialImageCacheBytes,
    required this.finalImageCacheBytes,
    required this.isMemoryStable,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  int get memoryDeltaBytes => finalImageCacheBytes - initialImageCacheBytes;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v10 Memory Footprint & Allocation Stability Audit');
    buf.writeln('- **Memory Status**: ${isMemoryStable ? "✅ MEMORY STABLE & LEAK-FREE" : "⚠️ ALLOCATION CHURN / LEAK DETECTED"}');
    buf.writeln('- **Rebuild Cycles Tested**: $cyclesExecuted');
    buf.writeln('- **Image Cache Initial**: ${(initialImageCacheBytes / 1024).toStringAsFixed(1)} KB');
    buf.writeln('- **Image Cache Final**: ${(finalImageCacheBytes / 1024).toStringAsFixed(1)} KB');
    buf.writeln('- **Memory Delta**: ${(memoryDeltaBytes / 1024).toStringAsFixed(1)} KB');
    return buf.toString();
  }
}

/// AQIL v10 Frontier 3: Memory Footprint & Garbage Collection Thrash Sentinel.
///
/// Drives rapid multi-cycle rebuilds and state transitions to audit memory stability,
/// imageCache blowup, and object churn.
abstract final class AqilGcThrashSentinel {
  /// Drives [cycles] rapid state rebuilds to verify memory and widget cache stability.
  static Future<GcThrashReport> auditAllocationStability(
    WidgetTester tester, {
    required Widget Function(BuildContext context, int cycle) builder,
    int cycles = 50,
  }) async {
    final initialBytes = PaintingBinding.instance.imageCache.currentSizeBytes;

    for (var i = 0; i < cycles; i++) {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Builder(builder: (ctx) => builder(ctx, i)),
          ),
        ),
      );
      await tester.pump();
    }

    final finalBytes = PaintingBinding.instance.imageCache.currentSizeBytes;
    // Allow modest image cache growth up to 10MB during testing
    final isStable = (finalBytes - initialBytes) < (10 * 1024 * 1024);

    return GcThrashReport(
      cyclesExecuted: cycles,
      initialImageCacheBytes: initialBytes,
      finalImageCacheBytes: finalBytes,
      isMemoryStable: isStable,
    );
  }
}
