import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Information regarding an element analyzed for visual saliency.
class SaliencyElementRecord {
  final String label;
  final Rect bounds;
  final double visualWeight;
  final bool isMarkedAsPrimary;

  const SaliencyElementRecord({
    required this.label,
    required this.bounds,
    required this.visualWeight,
    required this.isMarkedAsPrimary,
  });
}

/// Diagnostic report generated by [AqilVisualSaliencyAuditor.auditVisualFlow].
class SaliencyFlowReport {
  final SaliencyElementRecord? dominantElement;
  final List<SaliencyElementRecord> evaluatedElements;
  final bool primaryHasDominance;
  final double visualCompetitionRatio;
  final double cognitiveClutterScore; // 0 to 100 (lower is cleaner)
  final DateTime auditedAt;

  SaliencyFlowReport({
    required this.dominantElement,
    required this.evaluatedElements,
    required this.primaryHasDominance,
    required this.visualCompetitionRatio,
    required this.cognitiveClutterScore,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isClean => primaryHasDominance && cognitiveClutterScore < 45.0;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v8 Visual Saliency & Cognitive Flow Audit');
    buf.writeln('- **Flow Status**: ${isClean ? "✅ CLEAR COGNITIVE HIERARCHY" : "⚠️ VISUAL COMPETITION DETECTED"}');
    buf.writeln('- **Primary CTA Dominance**: ${primaryHasDominance ? "DOMINANT" : "SUBORDINATE / COMPETING"}');
    buf.writeln('- **Cognitive Clutter Score**: ${cognitiveClutterScore.toStringAsFixed(1)} / 100');
    buf.writeln('- **Visual Competition Ratio**: ${(visualCompetitionRatio * 100).toStringAsFixed(1)}%');
    buf.writeln('- **Dominant Visual Anchor**: ${dominantElement?.label ?? "None"} (Weight: ${dominantElement?.visualWeight.toStringAsFixed(1)})');
    buf.writeln();

    buf.writeln('| Element | Role | Area (dp²) | Visual Weight | Rank |');
    buf.writeln('| :--- | :--- | :--- | :--- | :--- |');
    final sorted = List<SaliencyElementRecord>.from(evaluatedElements)
      ..sort((a, b) => b.visualWeight.compareTo(a.visualWeight));
    for (var i = 0; i < sorted.length; i++) {
      final el = sorted[i];
      final area = el.bounds.width * el.bounds.height;
      final role = el.isMarkedAsPrimary ? '⭐ Primary CTA' : 'Secondary / Supporting';
      buf.writeln('| `${el.label}` | $role | ${area.toStringAsFixed(0)} | ${el.visualWeight.toStringAsFixed(1)} | #${i + 1} |');
    }
    return buf.toString();
  }
}

/// AQIL v8 Frontier 3: Autonomous Cognitive Saliency & Visual Flow Auditor.
///
/// Computes focal saliency weights based on spatial area, positioning, and visual contrast
/// to verify that primary user actions dominate cognitive visual flow.
abstract final class AqilVisualSaliencyAuditor {
  /// Audits cognitive visual hierarchy and asserts that [primaryCtaFinder] dominates the viewport.
  static SaliencyFlowReport auditVisualFlow(
    WidgetTester tester, {
    required Finder primaryCtaFinder,
    List<Finder> competingFinders = const [],
  }) {
    expect(primaryCtaFinder, findsWidgets);

    final evaluated = <SaliencyElementRecord>[];

    // 1. Calculate primary CTA weight
    final primaryBox = tester.renderObject(primaryCtaFinder.first) as RenderBox;
    final primaryRect = primaryBox.localToGlobal(Offset.zero) & primaryBox.size;
    final primaryArea = primaryRect.width * primaryRect.height;
    // Primary weight factors: area + elevated prominence boost
    final primaryWeight = math.sqrt(primaryArea) * 1.5;

    final primaryRecord = SaliencyElementRecord(
      label: 'Primary CTA: ${_describeFinder(primaryCtaFinder)}',
      bounds: primaryRect,
      visualWeight: primaryWeight,
      isMarkedAsPrimary: true,
    );
    evaluated.add(primaryRecord);

    // 2. Calculate competing elements' weights
    double maxCompetitorWeight = 0.0;
    for (final f in competingFinders) {
      if (f.evaluate().isEmpty) continue;
      final box = tester.renderObject(f.first) as RenderBox;
      final rect = box.localToGlobal(Offset.zero) & box.size;
      final area = rect.width * rect.height;
      final weight = math.sqrt(area);

      if (weight > maxCompetitorWeight) {
        maxCompetitorWeight = weight;
      }

      evaluated.add(SaliencyElementRecord(
        label: _describeFinder(f),
        bounds: rect,
        visualWeight: weight,
        isMarkedAsPrimary: false,
      ));
    }

    // Determine dominance
    final isDominant = primaryWeight >= maxCompetitorWeight;
    final competitionRatio = primaryWeight > 0 ? (maxCompetitorWeight / primaryWeight) : 1.0;

    // Cognitive clutter index: function of total element density and weight variance
    final clutterScore = math.min(100.0, (evaluated.length * 7.5) + (competitionRatio > 0.85 ? 25.0 : 0.0));

    SaliencyElementRecord dominant = primaryRecord;
    for (final el in evaluated) {
      if (el.visualWeight > dominant.visualWeight) {
        dominant = el;
      }
    }

    return SaliencyFlowReport(
      dominantElement: dominant,
      evaluatedElements: evaluated,
      primaryHasDominance: isDominant,
      visualCompetitionRatio: competitionRatio,
      cognitiveClutterScore: clutterScore,
    );
  }

  static String _describeFinder(Finder finder) {
    final desc = finder.toString();
    return desc.replaceAll(RegExp(r'\s+'), ' ');
  }
}
