import 'dart:io';

/// Target screen metadata discovered for automated pipeline test generation.
class PipelineScreenTarget {
  final String className;
  final String filePath;
  final String relativeImport;
  final bool hasConstConstructor;

  const PipelineScreenTarget({
    required this.className,
    required this.filePath,
    required this.relativeImport,
    required this.hasConstConstructor,
  });
}

/// Automated Screen Discovery and Test Suite Generator.
///
/// Crawls any Flutter project, discovers UI screens and pages,
/// and synthesizes a comprehensive `test/aqil_ui_pipeline_test.dart`
/// verifying all discovered screens across 5 viewports and 3 font scales.
class AqilTestGenerator {
  /// Discovers all screen and page widgets in target project.
  static List<PipelineScreenTarget> discoverScreens(String projectRoot) {
    final libDir = Directory('$projectRoot/lib');
    if (!libDir.existsSync()) return [];

    final discovered = <PipelineScreenTarget>[];

    final dartFiles = libDir
        .listSync(recursive: true, followLinks: false)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))
        .toList();

    // Regex for finding class declarations ending in Screen, View, Page
    final classRegex = RegExp(
      r'class\s+([A-Za-z0-9_]+(Screen|View|Page))\s+extends\s+(StatelessWidget|StatefulWidget)',
      multiLine: true,
    );

    for (final file in dartFiles) {
      final content = file.readAsStringSync();
      final matches = classRegex.allMatches(content);

      for (final match in matches) {
        final className = match.group(1)!;

        // Skip internal/private widgets
        if (className.startsWith('_')) continue;

        final hasConst = content.contains('const $className(');

        final relativePath = file.path
            .replaceAll('\\', '/')
            .replaceFirst('${libDir.path.replaceAll('\\', '/')}/', '');

        discovered.add(PipelineScreenTarget(
          className: className,
          filePath: file.path,
          relativeImport: relativePath,
          hasConstConstructor: hasConst,
        ));
      }
    }

    return discovered;
  }

  /// Generates or updates `test/aqil_ui_pipeline_test.dart` in the project.
  static File generatePipelineTestFile({
    required String projectRoot,
    required String packageName,
    required List<PipelineScreenTarget> screens,
  }) {
    final testDir = Directory('$projectRoot/test');
    if (!testDir.existsSync()) {
      testDir.createSync(recursive: true);
    }

    final targetFile = File('${testDir.path}/aqil_ui_pipeline_test.dart');

    final importsBuffer = StringBuffer();
    importsBuffer.writeln('import \'package:flutter/material.dart\';');
    importsBuffer.writeln('import \'package:flutter_test/flutter_test.dart\';');
    importsBuffer.writeln('import \'package:aqil_core/aqil_core.dart\';');

    final testCasesBuffer = StringBuffer();

    for (final screen in screens) {
      importsBuffer.writeln('import \'package:$packageName/${screen.relativeImport}\';');

      final constructorCall =
          screen.hasConstConstructor ? 'const ${screen.className}()' : '${screen.className}()';

      testCasesBuffer.writeln('''
    testAqilScreen(
      '${screen.className} renders with zero layout overflow across all viewports',
      builder: (context) => Scaffold(
        body: $constructorCall,
      ),
    );
''');
    }

    final generatedContent = '''// ==============================================================================
// AUTOMATICALLY GENERATED BY AQIL v12 FLEET PIPELINE GENERATOR
// Single source of truth: D:/Program/Antigravity/aqil_core_v10
// Tests all discovered screens across 5 viewports, 3 font scales, and theme matrix.
// ==============================================================================

$importsBuffer

void main() {
  group('AQIL Universal Automated Screen Pipeline [${screens.length} Screens]', () {
$testCasesBuffer
  });
}
''';

    targetFile.writeAsStringSync(generatedContent);
    return targetFile;
  }
}
