import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Categories of physical IoT, kiosk, and mobile hardware peripherals.
enum HardwarePeripheralType {
  cameraSensor,
  nfcRfidReader,
  thermalPrinter,
  usbBiometricScanner,
  ambientLightSensor,
  batterySubsystem,
  networkInterfaceCard,
}

/// Operational status states of a hardware peripheral.
enum PeripheralStatus {
  operational,
  disconnected,
  errorFault,
  degradedPerformance,
  overheating,
  outOfPaper,
  permissionDenied,
}

/// A synthetic fault condition injected into the hardware simulation mesh.
class HardwareFaultInjection {
  final HardwarePeripheralType peripheral;
  final PeripheralStatus targetStatus;
  final String simulatedErrorMessage;
  final Duration duration;
  final int retryAfterMs;

  const HardwareFaultInjection({
    required this.peripheral,
    required this.targetStatus,
    this.simulatedErrorMessage = 'Peripheral hardware fault / disconnected',
    this.duration = const Duration(milliseconds: 300),
    this.retryAfterMs = 1000,
  });
}

/// Real-time state event emitted by the hardware mesh to widgets and controllers.
class PeripheralStateEvent {
  final HardwarePeripheralType peripheral;
  final PeripheralStatus status;
  final String? diagnosticMessage;
  final DateTime timestamp;

  PeripheralStateEvent({
    required this.peripheral,
    required this.status,
    this.diagnosticMessage,
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  bool get isHealthy => status == PeripheralStatus.operational;
}

/// Diagnostic report generated by [AqilHardwareSensorMesh.auditHardwareFaultResilience].
class HardwareMeshReport {
  final int totalFaultsInjected;
  final int recoveredFaults;
  final bool displayedFallbackUi;
  final bool handledWithoutCrash;
  final List<String> eventTrail;
  final double resilienceScore;
  final DateTime auditedAt;

  HardwareMeshReport({
    required this.totalFaultsInjected,
    required this.recoveredFaults,
    required this.displayedFallbackUi,
    required this.handledWithoutCrash,
    required this.eventTrail,
    required this.resilienceScore,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isResilient => handledWithoutCrash && displayedFallbackUi && resilienceScore >= 80.0;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v8 Hardware Peripheral Resilience Report');
    buf.writeln('- **Resilience Status**: ${isResilient ? "✅ RESILIENT & ROBUST" : "⚠️ HARDWARE FAULT SENSITIVE"}');
    buf.writeln('- **Fault Recovery Score**: ${resilienceScore.toStringAsFixed(1)} / 100');
    buf.writeln('- **Faults Injected**: $totalFaultsInjected');
    buf.writeln('- **Faults Recovered**: $recoveredFaults');
    buf.writeln('- **Fallback UI Rendered**: $displayedFallbackUi');
    buf.writeln('- **Unhandled Fatal Crashes**: ${handledWithoutCrash ? 0 : 1}');
    buf.writeln();
    if (eventTrail.isNotEmpty) {
      buf.writeln('**Hardware Event Sequence**:');
      for (final ev in eventTrail) {
        buf.writeln('- $ev');
      }
    }
    return buf.toString();
  }
}

/// Mock hardware broker for injecting hardware states into UI during testing.
class HardwarePeripheralBroker {
  final _controller = StreamController<PeripheralStateEvent>.broadcast();
  final Map<HardwarePeripheralType, PeripheralStatus> _currentStates = {};

  Stream<PeripheralStateEvent> get stream => _controller.stream;

  PeripheralStatus getStatus(HardwarePeripheralType type) =>
      _currentStates[type] ?? PeripheralStatus.operational;

  void emitStatus(HardwarePeripheralType type, PeripheralStatus status, [String? message]) {
    _currentStates[type] = status;
    _controller.add(PeripheralStateEvent(
      peripheral: type,
      status: status,
      diagnosticMessage: message,
    ));
  }

  void dispose() {
    _controller.close();
  }
}

/// AQIL v8 Frontier 1: Live Hardware Sensor & Peripheral Mocking Mesh.
///
/// Injects edge hardware states (camera disconnect, low light, printer failure,
/// RFID reader timeout) into interactive widgets to evaluate fallback UI and recovery.
abstract final class AqilHardwareSensorMesh {
  /// Executes hardware fault injection against an interactive widget, evaluating fallback UI.
  static Future<HardwareMeshReport> auditHardwareFaultResilience(
    WidgetTester tester, {
    required Widget Function(BuildContext context, HardwarePeripheralBroker broker) builder,
    required List<HardwareFaultInjection> faults,
    Finder? fallbackUiFinder,
  }) async {
    final broker = HardwarePeripheralBroker();
    final eventTrail = <String>[];
    bool fallbackRendered = false;
    bool hadFatalCrash = false;
    int recoveredCount = 0;

    try {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Builder(builder: (context) => builder(context, broker)),
          ),
        ),
      );
      await tester.pumpAndSettle();
      eventTrail.add('Baseline: Initialized peripheral broker in operational state.');

      for (final fault in faults) {
        eventTrail.add('Injecting Fault: ${fault.peripheral.name} -> ${fault.targetStatus.name} (${fault.simulatedErrorMessage})');
        broker.emitStatus(fault.peripheral, fault.targetStatus, fault.simulatedErrorMessage);
        await tester.pump();
        await tester.pump(fault.duration);

        // Check if fallback UI rendered
        final fallbackFound = fallbackUiFinder != null
            ? fallbackUiFinder.evaluate().isNotEmpty
            : (find.byIcon(Icons.warning).evaluate().isNotEmpty ||
               find.byIcon(Icons.error_outline).evaluate().isNotEmpty ||
               find.textContaining(RegExp(r'fault', caseSensitive: false)).evaluate().isNotEmpty ||
               find.textContaining(RegExp(r'offline', caseSensitive: false)).evaluate().isNotEmpty ||
               find.textContaining(RegExp(r'disconnected', caseSensitive: false)).evaluate().isNotEmpty);

        if (fallbackFound) {
          fallbackRendered = true;
          eventTrail.add('Fallback Verified: UI displayed error/warning state for ${fault.peripheral.name}.');
        }

        // Simulate recovery
        eventTrail.add('Recovering: Restoring ${fault.peripheral.name} to operational status.');
        broker.emitStatus(fault.peripheral, PeripheralStatus.operational, 'Peripheral recovered');
        await tester.pump();
        await tester.pump(const Duration(milliseconds: 100));
        recoveredCount++;
      }
    } catch (e) {
      hadFatalCrash = true;
      eventTrail.add('Fatal Crash Detected: $e');
    } finally {
      broker.dispose();
    }

    final total = faults.isNotEmpty ? faults.length : 1;
    final score = ((recoveredCount / total) * 50.0) +
        (fallbackRendered ? 30.0 : 0.0) +
        (!hadFatalCrash ? 20.0 : 0.0);

    return HardwareMeshReport(
      totalFaultsInjected: faults.length,
      recoveredFaults: recoveredCount,
      displayedFallbackUi: fallbackRendered,
      handledWithoutCrash: !hadFatalCrash,
      eventTrail: eventTrail,
      resilienceScore: score.clamp(0.0, 100.0),
    );
  }
}
