import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// Simulated network profiles for mobile and enterprise kiosk environments.
enum NetworkChaosProfile {
  broadbandFiber,     // 0ms jitter, 100Mbps, 0% drop
  cellular4gModerate, // 80ms latency, 15ms jitter, 1% drop
  cellular2gEdge,     // 1200ms latency, 300ms jitter, 8% drop
  flakyCaptivePortal, // HTTP 302 redirect / DNS timeout
  packetLossBlackhole,// 100% packet loss (simulated tunnel / basement)
}

/// Simulated response outcome when invoking a network action under chaos.
class NetworkChaosResult<T> {
  final T? data;
  final bool isSuccess;
  final int latencyMs;
  final String? errorMessage;

  const NetworkChaosResult({
    this.data,
    required this.isSuccess,
    required this.latencyMs,
    this.errorMessage,
  });
}

/// Diagnostic report generated by [AqilNetworkChaosEngine.auditNetworkChaosResilience].
class NetworkChaosReport {
  final NetworkChaosProfile profile;
  final int totalRequests;
  final int failedRequests;
  final bool displayedErrorOrRetry;
  final bool handledWithoutUncaughtException;
  final double resilienceScore;
  final DateTime auditedAt;

  NetworkChaosReport({
    required this.profile,
    required this.totalRequests,
    required this.failedRequests,
    required this.displayedErrorOrRetry,
    required this.handledWithoutUncaughtException,
    required this.resilienceScore,
    DateTime? auditedAt,
  }) : auditedAt = auditedAt ?? DateTime.now();

  bool get isResilient =>
      handledWithoutUncaughtException &&
      displayedErrorOrRetry &&
      resilienceScore >= 80.0;

  String toMarkdownReport() {
    final buf = StringBuffer();
    buf.writeln('### AQIL v10 Network Chaos & Latency Jitter Audit');
    buf.writeln('- **Profile Simulated**: ${profile.name}');
    buf.writeln('- **Resilience Status**: ${isResilient ? "✅ RESILIENT UNDER CHAOS" : "⚠️ CHAOS DEFECT DETECTED"}');
    buf.writeln('- **Score**: ${resilienceScore.toStringAsFixed(1)} / 100');
    buf.writeln('- **Requests Evaluated**: $totalRequests (Failed: $failedRequests)');
    buf.writeln('- **Fallback / Retry UI Rendered**: $displayedErrorOrRetry');
    buf.writeln('- **Handled Without Crash**: $handledWithoutUncaughtException');
    return buf.toString();
  }
}

/// AQIL v10 Frontier 1: Network Chaos & Micro-Packet Loss Latency Jitter Engine.
///
/// Injects 2G latency, packet drop, and captive portal blackholes into widget data flows
/// to verify timeout handling, retry countdowns, and non-blocking loading states.
abstract final class AqilNetworkChaosEngine {
  /// Simulates network execution under the specified chaos profile.
  static Future<NetworkChaosResult<T>> simulateRequest<T>({
    required Future<T> Function() request,
    NetworkChaosProfile profile = NetworkChaosProfile.cellular2gEdge,
    math.Random? random,
  }) async {
    final rng = random ?? math.Random();

    switch (profile) {
      case NetworkChaosProfile.broadbandFiber:
        final res = await request();
        return NetworkChaosResult(data: res, isSuccess: true, latencyMs: 25);

      case NetworkChaosProfile.cellular4gModerate:
        final latency = 80 + rng.nextInt(30);
        await Future.delayed(Duration(milliseconds: latency));
        final res = await request();
        return NetworkChaosResult(data: res, isSuccess: true, latencyMs: latency);

      case NetworkChaosProfile.cellular2gEdge:
        final latency = 800 + rng.nextInt(600);
        await Future.delayed(Duration(milliseconds: latency));
        // 10% packet drop
        if (rng.nextDouble() < 0.10) {
          return NetworkChaosResult(
            isSuccess: false,
            latencyMs: latency,
            errorMessage: '2G connection timeout (packet loss)',
          );
        }
        final res = await request();
        return NetworkChaosResult(data: res, isSuccess: true, latencyMs: latency);

      case NetworkChaosProfile.flakyCaptivePortal:
        return const NetworkChaosResult(
          isSuccess: false,
          latencyMs: 150,
          errorMessage: 'Captive portal detected: HTTP 302 redirect to login.wifi',
        );

      case NetworkChaosProfile.packetLossBlackhole:
        return const NetworkChaosResult(
          isSuccess: false,
          latencyMs: 3000,
          errorMessage: 'Connection timed out: server unreachable',
        );
    }
  }

  /// Audits whether an interactive screen properly handles network errors and displays retry UI.
  static Future<NetworkChaosReport> auditNetworkChaosResilience(
    WidgetTester tester, {
    required Widget Function(BuildContext context, bool simulateError) builder,
    NetworkChaosProfile profile = NetworkChaosProfile.cellular2gEdge,
  }) async {
    bool hasRetryUi = false;
    bool handledWithoutCrash = true;

    try {
      // 1. Pump screen in error state
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Builder(builder: (ctx) => builder(ctx, true)),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // Check for error text or retry button
      final retryFound = find.textContaining(RegExp(r'retry|try again|offline|error', caseSensitive: false)).evaluate().isNotEmpty ||
          find.byIcon(Icons.refresh).evaluate().isNotEmpty ||
          find.byIcon(Icons.wifi_off).evaluate().isNotEmpty;

      if (retryFound) {
        hasRetryUi = true;
      }
    } catch (_) {
      handledWithoutCrash = false;
    }

    final score = (hasRetryUi ? 60.0 : 20.0) + (handledWithoutCrash ? 40.0 : 0.0);

    return NetworkChaosReport(
      profile: profile,
      totalRequests: 1,
      failedRequests: 1,
      displayedErrorOrRetry: hasRetryUi,
      handledWithoutUncaughtException: handledWithoutCrash,
      resilienceScore: score.clamp(0.0, 100.0),
    );
  }
}
