import 'package:flutter/foundation.dart';

/// Remediation rule category identifying the root cause of an AQIL violation.
enum RemediationRule {
  textEllipsisSafeguard,
  rowFlexOverflowWrap,
  columnScrollableWrap,
  minTouchTargetPadding,
  accessibleTooltip,
  metadataJoin,
  colorTokenization,
}

/// A deterministic source code patch generated by [AqilSelfHealer].
class RemediationPatch {
  final RemediationRule rule;
  final String description;
  final String originalSnippet;
  final String replacementSnippet;
  final double confidence; // 0.0 to 1.0

  const RemediationPatch({
    required this.rule,
    required this.description,
    required this.originalSnippet,
    required this.replacementSnippet,
    this.confidence = 1.0,
  });

  @override
  String toString() =>
      'RemediationPatch[${rule.name}] (${(confidence * 100).toInt()}%): $description';
}

/// Detailed execution outcome of an autonomous self-healing pass.
class SelfHealingResult {
  final bool success;
  final String originalSource;
  final String healedSource;
  final List<RemediationPatch> appliedPatches;
  final String diagnosticMessage;

  const SelfHealingResult({
    required this.success,
    required this.originalSource,
    required this.healedSource,
    required this.appliedPatches,
    required this.diagnosticMessage,
  });

  bool get hasModifications => originalSource != healedSource;
  int get patchCount => appliedPatches.length;
}

/// Autonomous Self-Healing AST Engine (AQIL Frontier 1).
///
/// Automatically diagnoses UI violations (missing ellipsis, RenderFlex overflows,
/// undersized touch targets, unlabeled icons, hardcoded colors) and computes
/// surgical, non-destructive source code patches.
class AqilSelfHealer {
  /// Injects single-line ellipsis safeguards (`maxLines: 1, overflow: TextOverflow.ellipsis`)
  /// into an unsafeguarded `Text(...)` invocation.
  static RemediationPatch? healTextEllipsis(
    String source, {
    required String textSnippet,
  }) {
    if (!source.contains(textSnippet)) {
      return null;
    }

    // Check if the snippet already declares overflow
    if (textSnippet.contains('overflow:') || textSnippet.contains('TextOverflow.')) {
      return null;
    }

    // Find the closing parenthesis of the Text constructor
    final trimmed = textSnippet.trim();
    if (!trimmed.startsWith('Text(') || !trimmed.endsWith(')')) {
      return null;
    }

    final innerContent = trimmed.substring(5, trimmed.length - 1).trim();
    final replacement = 'Text($innerContent, maxLines: 1, overflow: TextOverflow.ellipsis)';

    return RemediationPatch(
      rule: RemediationRule.textEllipsisSafeguard,
      description: 'Add maxLines: 1 and overflow: TextOverflow.ellipsis safeguard to Text widget',
      originalSnippet: trimmed,
      replacementSnippet: replacement,
      confidence: 0.98,
    );
  }

  /// Wraps an unconstrained or overflowing child widget within a `Row` in `Expanded` or `Flexible`.
  static RemediationPatch? healRowFlexOverflow(
    String source, {
    required String childSnippet,
    bool useFlexible = false,
  }) {
    final trimmed = childSnippet.trim();
    if (!source.contains(trimmed)) {
      return null;
    }

    // If already wrapped in Expanded or Flexible, skip
    if (trimmed.startsWith('Expanded(') || trimmed.startsWith('Flexible(')) {
      return null;
    }

    final wrapper = useFlexible ? 'Flexible' : 'Expanded';
    final replacement = '$wrapper(child: $trimmed)';

    return RemediationPatch(
      rule: RemediationRule.rowFlexOverflowWrap,
      description: 'Wrap overflowing Row child in $wrapper to prevent RenderFlex overflow',
      originalSnippet: trimmed,
      replacementSnippet: replacement,
      confidence: 0.95,
    );
  }

  /// Wraps an overflowing `Column` in a `SingleChildScrollView` to prevent vertical viewport overflow.
  static RemediationPatch? healColumnOverflow(
    String source, {
    required String columnSnippet,
  }) {
    final trimmed = columnSnippet.trim();
    if (!source.contains(trimmed)) {
      return null;
    }

    if (trimmed.startsWith('SingleChildScrollView(')) {
      return null;
    }

    final replacement = 'SingleChildScrollView(child: $trimmed)';

    return RemediationPatch(
      rule: RemediationRule.columnScrollableWrap,
      description: 'Wrap overflowing Column in SingleChildScrollView to prevent vertical overflow',
      originalSnippet: trimmed,
      replacementSnippet: replacement,
      confidence: 0.95,
    );
  }

  /// Injects minimum touch target size constraints (≥ 48x48dp for Android / 44x44pt for iOS).
  static RemediationPatch? healTouchTargetSize(
    String source, {
    required String buttonSnippet,
    double minSize = 48.0,
  }) {
    final trimmed = buttonSnippet.trim();
    if (!source.contains(trimmed)) {
      return null;
    }

    if (trimmed.contains('minimumSize:') || trimmed.contains('BoxConstraints(')) {
      return null;
    }

    String replacement;
    if (trimmed.startsWith('IconButton(')) {
      final inner = trimmed.substring(11, trimmed.length - 1).trim();
      replacement =
          'IconButton($inner, constraints: const BoxConstraints(minWidth: ${minSize.toInt()}, minHeight: ${minSize.toInt()}))';
    } else if (trimmed.startsWith('FilledButton(') ||
        trimmed.startsWith('ElevatedButton(') ||
        trimmed.startsWith('OutlinedButton(') ||
        trimmed.startsWith('TextButton(')) {
      final type = trimmed.split('(').first;
      final inner = trimmed.substring(type.length + 1, trimmed.length - 1).trim();
      replacement =
          '$type($inner, style: $type.styleFrom(minimumSize: const Size($minSize, $minSize)))';
    } else {
      replacement = 'SizedBox(width: $minSize, height: $minSize, child: $trimmed)';
    }

    return RemediationPatch(
      rule: RemediationRule.minTouchTargetPadding,
      description: 'Enforce minimum accessible touch target size (≥ ${minSize}dp)',
      originalSnippet: trimmed,
      replacementSnippet: replacement,
      confidence: 0.92,
    );
  }

  /// Injects an accessible `tooltip:` label into an unlabeled `IconButton`.
  static RemediationPatch? healUnlabeledIconButton(
    String source, {
    required String iconButtonSnippet,
    required String semanticTooltip,
  }) {
    var trimmed = iconButtonSnippet.trim();
    if (!source.contains(trimmed)) {
      if (trimmed.startsWith('IconButton(')) {
        final innerFirstArg = trimmed
            .substring(11, trimmed.length - (trimmed.endsWith(')') ? 1 : 0))
            .split(',')
            .first
            .trim();
        final match = RegExp(
          'IconButton\\([^)]*?${RegExp.escape(innerFirstArg)}[^)]*?\\)',
        ).firstMatch(source);
        if (match != null) {
          trimmed = match.group(0)!;
        } else {
          return null;
        }
      } else {
        return null;
      }
    }

    if (trimmed.contains('tooltip:')) {
      return null;
    }

    if (!trimmed.startsWith('IconButton(') || !trimmed.endsWith(')')) {
      return null;
    }

    final inner = trimmed.substring(11, trimmed.length - 1).trim();
    final replacement = 'IconButton($inner, tooltip: \'$semanticTooltip\')';

    return RemediationPatch(
      rule: RemediationRule.accessibleTooltip,
      description: 'Add accessible tooltip label to IconButton (WCAG 2.2 AccName)',
      originalSnippet: trimmed,
      replacementSnippet: replacement,
      confidence: 0.99,
    );
  }

  /// Consolidates multiple unjoined metadata `Text` widgets into a single joined text element.
  static RemediationPatch? healMetadataRow(
    String source, {
    required String rowSnippet,
    required List<String> metadataVariables,
  }) {
    final trimmed = rowSnippet.trim();
    if (!source.contains(trimmed)) {
      return null;
    }

    final joinedExpression =
        '[${metadataVariables.join(', ')}].join(\' • \')';
    final replacement =
        'Text($joinedExpression, maxLines: 1, overflow: TextOverflow.ellipsis)';

    return RemediationPatch(
      rule: RemediationRule.metadataJoin,
      description: 'Join multi-part metadata row into a single Text with delimiter safeguard',
      originalSnippet: trimmed,
      replacementSnippet: replacement,
      confidence: 0.90,
    );
  }

  /// Replaces hardcoded color literals with semantic design system tokens.
  static RemediationPatch? healHardcodedColor(
    String source, {
    required String hardcodedLiteral,
    required String tokenReplacement,
  }) {
    if (!source.contains(hardcodedLiteral)) {
      return null;
    }

    return RemediationPatch(
      rule: RemediationRule.colorTokenization,
      description: 'Replace hardcoded color ($hardcodedLiteral) with token ($tokenReplacement)',
      originalSnippet: hardcodedLiteral,
      replacementSnippet: tokenReplacement,
      confidence: 1.0,
    );
  }

  /// Applies a sequence of deterministic non-overlapping patches to the source code.
  static SelfHealingResult applyPatches(
    String source,
    List<RemediationPatch> patches,
  ) {
    if (patches.isEmpty) {
      return SelfHealingResult(
        success: true,
        originalSource: source,
        healedSource: source,
        appliedPatches: const [],
        diagnosticMessage: 'No remediation patches needed; code is clean.',
      );
    }

    String healed = source;
    final applied = <RemediationPatch>[];

    for (final patch in patches) {
      if (healed.contains(patch.originalSnippet)) {
        healed = healed.replaceFirst(patch.originalSnippet, patch.replacementSnippet);
        applied.add(patch);
      } else {
        debugPrint('[AqilSelfHealer] Patch skipped (original snippet not found): ${patch.description}');
      }
    }

    final success = applied.isNotEmpty;
    return SelfHealingResult(
      success: success,
      originalSource: source,
      healedSource: healed,
      appliedPatches: applied,
      diagnosticMessage: 'Applied ${applied.length} of ${patches.length} planned patches successfully.',
    );
  }

  /// Comprehensive multi-rule automated scan and remediation pipeline.
  static SelfHealingResult scanAndHeal(
    String sourceCode, {
    List<String> unSafeguardedTexts = const [],
    List<String> overflowingRowChildren = const [],
    List<String> overflowingColumns = const [],
    List<String> undersizedButtons = const [],
    Map<String, String> unlabeledIconButtons = const {},
    Map<String, String> hardcodedColors = const {},
  }) {
    String currentCode = sourceCode;
    final allAppliedPatches = <RemediationPatch>[];

    // Pass 1: Text ellipsis safeguards
    for (final text in unSafeguardedTexts) {
      final patch = healTextEllipsis(currentCode, textSnippet: text);
      if (patch != null && currentCode.contains(patch.originalSnippet)) {
        currentCode = currentCode.replaceFirst(patch.originalSnippet, patch.replacementSnippet);
        allAppliedPatches.add(patch);
      }
    }

    // Pass 2: Row flex overflow wrap
    for (final rowChild in overflowingRowChildren) {
      final patch = healRowFlexOverflow(currentCode, childSnippet: rowChild);
      if (patch != null && currentCode.contains(patch.originalSnippet)) {
        currentCode = currentCode.replaceFirst(patch.originalSnippet, patch.replacementSnippet);
        allAppliedPatches.add(patch);
      }
    }

    // Pass 3: Column scrollable wrap
    for (final col in overflowingColumns) {
      final patch = healColumnOverflow(currentCode, columnSnippet: col);
      if (patch != null && currentCode.contains(patch.originalSnippet)) {
        currentCode = currentCode.replaceFirst(patch.originalSnippet, patch.replacementSnippet);
        allAppliedPatches.add(patch);
      }
    }

    // Pass 4: Touch targets
    for (final button in undersizedButtons) {
      final patch = healTouchTargetSize(currentCode, buttonSnippet: button);
      if (patch != null && currentCode.contains(patch.originalSnippet)) {
        currentCode = currentCode.replaceFirst(patch.originalSnippet, patch.replacementSnippet);
        allAppliedPatches.add(patch);
      }
    }

    // Pass 5: Accessible tooltips
    for (final entry in unlabeledIconButtons.entries) {
      final patch = healUnlabeledIconButton(
        currentCode,
        iconButtonSnippet: entry.key,
        semanticTooltip: entry.value,
      );
      if (patch != null && currentCode.contains(patch.originalSnippet)) {
        currentCode = currentCode.replaceFirst(patch.originalSnippet, patch.replacementSnippet);
        allAppliedPatches.add(patch);
      }
    }

    // Pass 6: Hardcoded colors
    for (final entry in hardcodedColors.entries) {
      final patch = healHardcodedColor(
        currentCode,
        hardcodedLiteral: entry.key,
        tokenReplacement: entry.value,
      );
      if (patch != null && currentCode.contains(patch.originalSnippet)) {
        currentCode = currentCode.replaceFirst(patch.originalSnippet, patch.replacementSnippet);
        allAppliedPatches.add(patch);
      }
    }

    return SelfHealingResult(
      success: allAppliedPatches.isNotEmpty,
      originalSource: sourceCode,
      healedSource: currentCode,
      appliedPatches: allAppliedPatches,
      diagnosticMessage: 'Applied ${allAppliedPatches.length} remediation patches successfully.',
    );
  }
}
